"""Apply W1-LEDGERLOCK-PLAN-V2.1 — the final plan revision — and record the base commit the V2.1 runs branch from.

Deterministic: the story cards and `stories.index.json` are regenerated by the product's own splitter (no model
call), the gates whose artifacts changed are re-approved through the product's own approval store, and the result is
one commit. The LedgerLock requirements and every delivered evidence commit are untouched — the base is the approved
plan commit, exactly as prepare_run_copy.sh uses it.

    python3 apply_plan_v2.py --project ~/Downloads/projects/ledgerlock-aiseftest-run2 \
        --epics closure-evidence/hardening/w1/plan-v2/epics-v2.1.md --base 1621a2bc --branch plan-v2.1 --out <record.json>
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT))

from aisef.config import Config  # noqa: E402
from aisef.control.approvals import ApprovalStore, Gate  # noqa: E402
from aisef.phases.story_split import split  # noqa: E402

#: The gates whose artifacts this revision rewrites. Everything upstream (PRD, architecture, UX) is untouched, so
#: its approval still binds the same bytes.
REAPPROVE = (Gate.EPICS, Gate.STORIES)


def git(project: Path, *args: str) -> str:
    r = subprocess.run(["git", *args], cwd=str(project), capture_output=True, text=True, encoding="utf-8")
    if r.returncode:
        raise SystemExit(f"git {' '.join(args)} failed: {r.stderr.strip()}")
    return r.stdout.strip()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True)
    ap.add_argument("--epics", required=True)
    ap.add_argument("--base", required=True, help="the approved V1 plan commit the runs branch from")
    ap.add_argument("--branch", default="plan-v2.1")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    project = Path(a.project).expanduser().resolve()
    root = project / "_bmad-output"

    dirty = git(project, "status", "--porcelain")
    if dirty:
        raise SystemExit(f"refused: {project} is dirty\n{dirty}")
    git(project, "checkout", "-q", "-B", a.branch, a.base)

    before = (root / "epics.md").read_text(encoding="utf-8")
    (root / "epics.md").write_text(Path(a.epics).read_text(encoding="utf-8"), encoding="utf-8")

    res = split(root, config=Config.load(project))
    if not res.ok:
        raise SystemExit("refused: the machine gate does not pass on this plan\n" + res.summary())

    store = ApprovalStore(root)
    approved = []
    for gate in REAPPROVE:
        rec = store.approve(gate, note="W1-LEDGERLOCK-PLAN-V2.1 (owner decision 2026-09-21, sections 3-5): the usage-error exit moves to its semantic introduction owner")
        approved.append({"gate": gate.value, "by": rec.decided_by})

    git(project, "add", "-A")
    git(project, "commit", "-q", "-m",
        "W1-LEDGERLOCK-PLAN-V2.1: the usage-error exit is owned by the story whose argparse surface introduces it "
        "(STORY-01-01, FR-12), and STORY-04-01 preserves it instead of claiming to introduce it")
    head = git(project, "rev-parse", "HEAD")

    rec = {"record": "W1-LEDGERLOCK-PLAN-V2.1 applied", "generated": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
           "project": str(project), "branch": a.branch, "base_commit": git(project, "rev-parse", a.base),
           "plan_v2_1_commit": head, "epics_changed": before != (root / "epics.md").read_text(encoding="utf-8"),
           "stories": len(res.stories), "story_files": len(res.files),
           "machine_gate": {"passed": res.gate.passed, "errors": res.gate.errors, "warnings": res.gate.warnings},
           "reapproved_gates": approved,
           "requirements_untouched": not git(project, "diff", "--name-only", f"{a.base}..HEAD", "--", "docs/")}
    Path(a.out).write_text(json.dumps(rec, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(json.dumps({k: rec[k] for k in ("plan_v2_1_commit", "stories", "reapproved_gates", "requirements_untouched")}))
    for w in res.gate.warnings:
        print("  ⚠", w)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
