"""Run commands in an isolated environment.

Everything the agent runs — tests, linters, security scans — goes through
here. The goal is not to defend against a determined attacker, but to block
the things that routinely happen when an agent works autonomously: unexpected
network calls, writing files outside the story scope, or privilege escalation
via a sloppy install script.

Four privilege levels, ascending (SOLUTION section 5.3). Principle: **choose
the lowest level that suffices**, not the most convenient one.

Two clearly separated layers (ADR-005 V5, inspired by SWE-ReX/Harbor):

* **Level declares requirements** — ``Level.requires()`` returns the set of
  ``Guarantee``s that level needs: no network, read-only, non-root, etc.
* **Provider declares capabilities** — ``ExecutionProvider.guarantees(level)``
  honestly reports what it can guarantee at that level (``Support`` from
  ``clients/base.py``: read the actual name, do not infer).

``run()`` compares the two layers: any missing guarantee sets
``degraded=True`` **with the missing guarantee names** in
``SandboxResult.missing`` — "degraded" without saying what is missing means
the evidence reader does not know what they are trusting (invariant 10).
``allow_degraded=False`` fails immediately at provider selection, before any
command runs.

Three providers: ``docker`` (default), ``local`` (runs directly, all
guarantees UNSUPPORTED), ``fake`` (for tests, returns scripted results).
External backends declare ``"module:Class"`` in ``sandbox.provider``. No
sessions, no daemon: one command, one run. ``host`` (runs on the real
machine, declares NATIVE) is used only by the unit test suite —
``tests/__init__.py`` — not a project-level choice.

Docker guarantees have been verified by real runs, see
``docs/SANDBOX-CONFORMANCE.md`` (S1–S5, generated by
``python3 -m tests.sandbox_conformance``) and ``tests/test_sandbox.py``
``TestIsolation`` (marked ``needs_docker``).
"""

from __future__ import annotations

import importlib
import os
import shutil
import subprocess
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Protocol

from ..clients.base import Support, runnable

#: Default image: small, typically pre-pulled on dev machines.
DEFAULT_IMAGE = "alpine:latest"

#: Unprivileged user inside the container.
SANDBOX_UID_GID = "1000:1000"


class Guarantee(str, Enum):
    """A guarantee a provider can offer when running a command."""

    NETWORK_NONE = "network_none"        # no network access, including DNS
    READ_ONLY_FS = "read_only_fs"        # cannot write to workspace
    NON_ROOT = "non_root"                # no root, no capabilities
    NO_HOST_MOUNT = "no_host_mount"      # cannot see host disk (worktree mount is by design -> Docker also lacks this)
    SECRETS_ABSENT = "secrets_absent"    # env inside contains only `spec.env`, does not inherit host env


class Level(str, Enum):
    """Privilege levels, ascending."""

    READ_ONLY = "READ_ONLY"                  # read-only, no network
    WORKSPACE_WRITE = "WORKSPACE_WRITE"      # write within workspace, no network
    WORKSPACE_NETWORK = "WORKSPACE_NETWORK"  # write + network (install deps)
    PRIVILEGED_TEST = "PRIVILEGED_TEST"      # for tests that need elevated privileges

    @property
    def writable(self) -> bool:
        return self is not Level.READ_ONLY

    @property
    def networked(self) -> bool:
        return self in (Level.WORKSPACE_NETWORK, Level.PRIVILEGED_TEST)

    def requires(self) -> set[Guarantee]:
        """Guarantees this level **requires** — any the provider lacks is degraded.

        All levels require ``SECRETS_ABSENT``: no level has a reason to receive
        host secrets. ``NO_HOST_MOUNT`` is not required by any level — the
        worktree mount is by design, but providers still declare it so the
        capability table is honest."""
        need = {Guarantee.SECRETS_ABSENT}
        if not self.networked:
            need.add(Guarantee.NETWORK_NONE)
        if not self.writable:
            need.add(Guarantee.READ_ONLY_FS)
        if self is not Level.PRIVILEGED_TEST:
            need.add(Guarantee.NON_ROOT)
        return need


@dataclass
class SandboxSpec:
    workspace: Path
    cmd: list[str]
    level: Level = Level.WORKSPACE_WRITE
    image: str = DEFAULT_IMAGE
    env: dict[str, str] = field(default_factory=dict)
    timeout_seconds: int = 1800
    #: Allow degraded execution — run on a provider missing guarantees for
    #: this level. Set False when isolation is mandatory and failing is
    #: preferable to running without guarantees: the error fires at provider
    #: selection, before any command runs.
    allow_degraded: bool = True
    #: Whether to use Docker. Set False when the project's toolchain only
    #: runs on the host — e.g. dependencies with host-arch-compiled binaries
    #: that break inside a Linux container. Equivalent to ``provider="local"``;
    #: kept for backward compatibility with existing configs.
    use_docker: bool = True
    #: Provider name (``docker`` · ``local`` · ``fake`` · ``"module:Class"``).
    #: Empty = ``docker``, falls back to ``local`` when ``use_docker=False``.
    provider: str = ""
    #: Extra directories mounted into the workspace: `relative path in
    #: workspace -> host path`. For clean worktrees built from a SHA (ADR-005
    #: V6): they lack `node_modules`/venv — not in git — so borrow from the
    #: project as the normal tree would have. Docker: bind mount with the same
    #: mode as workspace; degraded: symlink in workspace (only if slot is
    #: empty). Use only for temp trees the harness owns — symlinks leave traces.
    mounts: dict[str, Path] = field(default_factory=dict)


@dataclass
class SandboxResult:
    exit_code: int
    stdout: str = ""
    stderr: str = ""
    duration_ms: int = 0
    degraded: bool = False
    timed_out: bool = False
    #: ``"<provider>/<level>"`` — e.g. ``docker/WORKSPACE_WRITE``, ``local/READ_ONLY``.
    isolation: str = ""
    #: Guarantee names required by this level that the provider lacks. Empty when all met.
    missing: list[str] = field(default_factory=list)
    #: **Infrastructure** error — daemon unresponsive, cannot pull image —
    #: distinct from the command exiting non-zero. Conflating the two means
    #: "test failed" turns out to be Docker broken, and someone fixes tests
    #: when the fix belongs to the machine (SWE-ReX 511).
    provider_error: str = ""

    @property
    def ok(self) -> bool:
        return self.exit_code == 0 and not self.timed_out

    def to_evidence(self) -> dict:
        return {
            "exit_code": self.exit_code,
            "ok": self.ok,
            "duration_ms": self.duration_ms,
            "isolation": self.isolation,
            "degraded": self.degraded,
            "missing": list(self.missing),
            "timed_out": self.timed_out,
            "provider_error": self.provider_error,
        }


class ExecutionProvider(Protocol):
    """A way to run commands. Honestly declares its guarantees; ``run`` once."""

    id: str

    def available(self) -> bool: ...

    def guarantees(self, level: Level) -> dict[Guarantee, Support]: ...

    def run(self, spec: SandboxSpec) -> SandboxResult: ...


def docker_available() -> bool:
    """True when both the CLI and daemon are available."""
    if not shutil.which("docker"):
        return False
    try:
        return subprocess.run(
            ["docker", "info"], capture_output=True, timeout=10
        ).returncode == 0
    except (subprocess.TimeoutExpired, OSError):
        return False


def build_docker_args(spec: SandboxSpec, *, name: str = "") -> list[str]:
    """Build the docker command line. Separated so it can be tested without running."""
    ws = str(Path(spec.workspace).resolve())
    mount_mode = "rw" if spec.level.writable else "ro"

    args = [
        "docker", "run", "--rm",
        "-v", f"{ws}:/workspace:{mount_mode}",
        "-w", "/workspace",
    ]
    if name:
        args += ["--name", name]
    for rel, src in spec.mounts.items():
        args += ["-v", f"{Path(src).resolve()}:/workspace/{rel}:{mount_mode}"]

    if not spec.level.networked:
        args += ["--network=none"]

    if spec.level is not Level.PRIVILEGED_TEST:
        args += ["--cap-drop=ALL", "--user", SANDBOX_UID_GID]

    # Only `spec.env` enters the container — host env is not inherited.
    # This is the entire basis of the SECRETS_ABSENT guarantee; do not add
    # `--env-file`/`-e KEY` (without value) here, docker would pull from host.
    for k, v in spec.env.items():
        args += ["-e", f"{k}={v}"]

    args.append(spec.image)
    args += spec.cmd
    return args


class DockerProvider:
    """Single-use container: mounts worktree, non-root, network disabled per level."""

    id = "docker"

    def available(self) -> bool:
        return docker_available()

    def guarantees(self, level: Level) -> dict[Guarantee, Support]:
        on = Support.NATIVE
        off = Support.UNSUPPORTED
        return {
            Guarantee.NETWORK_NONE: off if level.networked else on,
            Guarantee.READ_ONLY_FS: on if not level.writable else off,
            Guarantee.NON_ROOT: off if level is Level.PRIVILEGED_TEST else on,
            Guarantee.NO_HOST_MOUNT: off,  # worktree mount is by design
            Guarantee.SECRETS_ABSENT: on,  # `-e` only passes `spec.env`
        }

    def run(self, spec: SandboxSpec) -> SandboxResult:
        return _run_docker(spec)


class LocalProvider:
    """Runs directly on the host. No guarantees — only limits the working directory."""

    id = "local"

    def available(self) -> bool:
        return True

    def guarantees(self, level: Level) -> dict[Guarantee, Support]:
        return {g: Support.UNSUPPORTED for g in Guarantee}

    def run(self, spec: SandboxSpec) -> SandboxResult:
        return _run_degraded(spec)


class FakeProvider:
    """Returns scripted results, declares all guarantees NATIVE — lets
    `gate`/`qa`/`tools` tests run without Docker. Exhausted scripts repeat
    the last result; no scripts means all commands pass. ``calls`` records
    each invocation's spec so tests can verify privilege levels and commands."""

    id = "fake"

    def __init__(self, outputs: list[SandboxResult] | None = None):
        self.outputs = list(outputs or [])
        self.calls: list[SandboxSpec] = []

    def available(self) -> bool:
        return True

    def guarantees(self, level: Level) -> dict[Guarantee, Support]:
        return {g: Support.NATIVE for g in Guarantee}

    def run(self, spec: SandboxSpec) -> SandboxResult:
        self.calls.append(spec)
        if not self.outputs:
            return SandboxResult(exit_code=0)
        out = self.outputs.pop(0) if len(self.outputs) > 1 else self.outputs[0]
        return SandboxResult(**{k: v for k, v in vars(out).items()})


class HostProvider(LocalProvider):
    """**Unit tests only** — simulates isolation. Runs real commands via
    subprocess on the host like ``local``, but declares all guarantees NATIVE
    so results are not ``degraded`` despite no container. Acceptable because
    the unit suite tests **harness rules** (what evidence records, what gates
    read, "unrunnable != red"), not Docker; real Docker is tested by
    ``needs_docker``-marked tests (``AISEF_TEST_DOCKER=1``) and conformance
    S1–S5. Each container takes 6–18s on the bench machine, full suite 25–60
    min — that is why this exists (release plan A2). Not in ``PROVIDERS``:
    ``sandbox.provider = "host"`` in a project is rejected as an unknown name;
    ``tests/__init__.py`` swaps it in place of ``docker``."""

    id = "host"

    def guarantees(self, level: Level) -> dict[Guarantee, Support]:
        return {g: Support.NATIVE for g in Guarantee}


#: Providers by name. Tests register `fake` via `using()`; external backends
#: go through `import_path` and are cached here after the first load.
PROVIDERS: dict[str, ExecutionProvider] = {
    "docker": DockerProvider(),
    "local": LocalProvider(),
}


def resolve_provider(name: str) -> ExecutionProvider:
    """``docker`` · ``local`` · registered name · ``"module:Class"`` (5 lines, Harbor-style factory)."""
    if name in PROVIDERS:
        return PROVIDERS[name]
    if ":" not in name:
        raise ValueError(
            f"sandbox.provider={name!r} does not exist; available: {', '.join(sorted(PROVIDERS))} "
            "or \"module:Class\""
        )
    mod, _, cls = name.partition(":")
    provider = getattr(importlib.import_module(mod), cls)()
    PROVIDERS[name] = provider
    return provider


class using:
    """Temporarily register a provider (typically ``FakeProvider``) under ``provider.id``.

        with sandbox.using(FakeProvider([...])) as fake:
            run_suite(..., config=Config({**DEFAULTS, "sandbox.provider": "fake"}))
    """

    def __init__(self, provider: ExecutionProvider):
        self.provider = provider

    def __enter__(self):
        self._prev = PROVIDERS.get(self.provider.id)
        PROVIDERS[self.provider.id] = self.provider
        return self.provider

    def __exit__(self, *exc):
        if self._prev is None:
            PROVIDERS.pop(self.provider.id, None)
        else:
            PROVIDERS[self.provider.id] = self._prev


def missing_guarantees(provider: ExecutionProvider, level: Level) -> list[str]:
    """Guarantee names ``level`` requires that ``provider`` cannot block at source."""
    have = provider.guarantees(level)
    return sorted(
        g.value for g in level.requires()
        if not have.get(g, Support.UNSUPPORTED).blocks_at_source
    )


def select_provider(spec: SandboxSpec) -> tuple[ExecutionProvider, list[str]]:
    """Select a provider and compute missing guarantees — **before** any command runs.

    When Docker's daemon is unavailable, fall back to ``local`` as before;
    but falling back is degraded, and ``allow_degraded=False`` rejects here
    with the missing guarantee names, without waiting for execution."""
    name = spec.provider or "docker"
    if name == "docker" and not spec.use_docker:
        name = "local"
    provider = resolve_provider(name)
    why = ""
    if not provider.available():
        if name == "local":
            raise RuntimeError("provider local not available — nothing to fall back to")
        why = "daemon not running" if name == "docker" else f"provider {name} not available"
        provider = resolve_provider("local")
    elif name == "local" and not spec.use_docker and not spec.provider:
        why = "configuration disabled Docker"

    missing = missing_guarantees(provider, spec.level)
    if missing and not spec.allow_degraded:
        raise RuntimeError(
            f"level {spec.level.value} requires isolation but provider {provider.id}"
            + (f" ({why})" if why else "")
            + f" is missing guarantees: {', '.join(missing)}"
            "; set allow_degraded=True to accept a lower assurance level"
        )
    return provider, missing


def run(spec: SandboxSpec) -> SandboxResult:
    """Run a command on the selected provider; result carries provider name, level, and missing guarantees."""
    workspace = Path(spec.workspace)
    if not workspace.is_dir():
        raise FileNotFoundError(f"workspace does not exist: {workspace}")
    if not spec.cmd:
        raise ValueError("cmd is empty")

    provider, missing = select_provider(spec)
    result = provider.run(spec)
    result.isolation = f"{provider.id}/{spec.level.value}"
    result.missing = missing
    result.degraded = bool(missing)
    return result


#: Docker CLI exits 125 when **docker itself** fails (daemon, image pull,
#: bad flags) — distinct from 126/127 and the inner command's exit code.
#: See `docker run` documentation.
_DOCKER_INFRA_EXIT = 125


def _run_docker(spec: SandboxSpec) -> SandboxResult:
    name = f"aisef-{uuid.uuid4().hex[:12]}"
    args = build_docker_args(spec, name=name)
    started = time.monotonic()
    try:
        proc = subprocess.run(
            args, capture_output=True, text=True, timeout=spec.timeout_seconds
        )
    except subprocess.TimeoutExpired:
        # Killing the CLI does not kill the container: `sleep 9999` would
        # keep running for ~3 hours holding the worktree mount. Verified in
        # S5 sandbox conformance.
        subprocess.run(["docker", "rm", "-f", name], capture_output=True, timeout=30)
        return SandboxResult(
            exit_code=124,
            stderr=f"exceeded {spec.timeout_seconds}s",
            duration_ms=int((time.monotonic() - started) * 1000),
            timed_out=True,
        )
    except OSError as e:
        return SandboxResult(
            exit_code=_DOCKER_INFRA_EXIT,
            stderr=str(e),
            duration_ms=int((time.monotonic() - started) * 1000),
            provider_error=f"cannot invoke docker: {e}",
        )
    provider_error = ""
    if proc.returncode == _DOCKER_INFRA_EXIT:
        last = [l for l in proc.stderr.strip().splitlines() if l.strip()]
        provider_error = (last[-1] if last else "docker exited 125").strip()[:300]
    return SandboxResult(
        exit_code=proc.returncode,
        stdout=proc.stdout,
        stderr=proc.stderr,
        duration_ms=int((time.monotonic() - started) * 1000),
        provider_error=provider_error,
    )


def _link_mounts(spec: SandboxSpec) -> None:
    """No bind mounts outside Docker: symlink into workspace instead.
    If the target already exists (project committed `node_modules`?) — do not overwrite."""
    for rel, src in spec.mounts.items():
        dst = Path(spec.workspace) / rel
        if not dst.exists() and not dst.is_symlink():
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.symlink_to(Path(src).resolve())


def _run_degraded(spec: SandboxSpec) -> SandboxResult:
    """Run directly on the host. No isolation — only limits the working directory."""
    _link_mounts(spec)
    started = time.monotonic()
    try:
        proc = subprocess.run(
            runnable(spec.cmd),
            cwd=str(spec.workspace),
            capture_output=True,
            text=True,
            timeout=spec.timeout_seconds,
            # Inherit host env then overlay `spec.env`. Previously `{**spec.env}
            # or None`: non-empty env lost PATH, commands outside /bin were
            # not found — and that is also why SECRETS_ABSENT is UNSUPPORTED here.
            env={**os.environ, **spec.env},
        )
    except subprocess.TimeoutExpired:
        return SandboxResult(
            exit_code=124,
            stderr=f"exceeded {spec.timeout_seconds}s",
            duration_ms=int((time.monotonic() - started) * 1000),
            timed_out=True,
        )
    except OSError as e:
        return SandboxResult(
            exit_code=127,
            stderr=str(e),
            duration_ms=int((time.monotonic() - started) * 1000),
        )
    return SandboxResult(
        exit_code=proc.returncode,
        stdout=proc.stdout,
        stderr=proc.stderr,
        duration_ms=int((time.monotonic() - started) * 1000),
    )
