"""Evidence-based epic improvement loop (ADR-004 R3): `aisef improve --epic E`.

HoH proved the "measure gap -> fix -> re-measure" loop creates gain, but running
T = 70 rounds with no stopping condition doesn't work.  Here the loop is
**composed** from existing pieces -- no new phase, no changes to `run`/`implement`
-- and stops by code:

    qa.run_suite (project-level evidence at HEAD) -> ledger.build() -> GAP/REOPENED
    belonging to epic -> **one** repair story generated by code -> run.run_epic (new
    session, worktree, gate, reviewer != developer) -> QA again ->
    ledger.snapshot("loop-n") -> next round.

Five stopping conditions, all read from disk (ledger, evidence), not from process
memory -- so re-running resumes from the right place, no daemon needed:

1. no GAP/REOPENED remaining in epic;
2. reached `improve.max_loops` (counted per epic from `loops[]`);
3. marginal improvement delta(verified) - delta(reopened) <= 0 for
   `improve.flat_loops` consecutive rounds;
4. total cost of epic rounds exceeds `improve.cost_cap_usd`;
5. repair story plan stuck (`[stuck]`, reviewer verified) -> return to human.

Each round **one** repair story = **one** behavior: B1 requires cost <= 1 story per
round, and one behavior is the smallest unit the gate can score.  REOPENED goes
before GAP -- regression is what HoH measures.  Repair story is **deterministically**
generated from gap; agent enters at R10 after gain is measured.

Human gate `improve` before each round >= 2 (unless `--auto`): pipeline stops at
gate, human reads `LOOP-REPORT-<n>.md`, `aisef approve improve`, reruns -- same
mechanism as the other eight gates, approval binds to report hash.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from ..clients.base import ClientAdapter
from ..config import Config
from ..control import complexity
from ..control import ledger as ledger_mod
from ..control.approvals import ApprovalStore, Gate, Status
from ..control.change import read_index, register_story
from ..control.journal import Entry, JournalStore, reconcile_all
from ..control.ledger import GAP, REOPENED, UNBUILT, UNTESTED, UNTRACED, Behavior, Ledger
from ..control.normalize import Story, verification_paths
from ..control.preflight import verification_contract
from ..control.qualification import (
    ApprovalSnapshot as QApproval,
    BehaviorGap as QGap,
    Inputs as QInputs,
    PHASE_REPAIR,
    Profile as QProfile,
    QaSnapshot as QQa,
    Verdict as QVerdict,
    qualify as q_qualify,
)
from ..control.state import StateStore, StoryStatus
from ..control.worktree import GitError, RunOwnedError, WorktreeManager, run_ownership
from ..harness.guardrails import head_sha
from ..harness.observe import EvidenceStore
from .implement import plan_defects
from .plan import ARTIFACT_ROOT
from .qa import KINDS as QA_KINDS, run_suite
from .run import RunReport, load_plan, run_epic

#: Baseline before the first round of a call.  Recorded when the ledger has
#: changed since the last baseline (stories usually run between two `improve`
#: calls) or the last baseline belongs to another epic, so the next round's
#: delta correctly measures what that round produced for that epic.
BASELINE = "loop-0"
LOOP_REPORT = "LOOP-REPORT-{n}.md"
STORY_PREFIX = "STORY-RP-"


def repair_epic(epic_id: str) -> str:
    """`EPIC-01` -> `EPIC-RP-01`."""
    return "EPIC-RP-" + epic_id.removeprefix("EPIC-")


@dataclass
class Loop:
    """One round: enough to write the report and for the human to decide continue or stop."""

    n: int                      # label `loop-<n>` in ledger -- global, unique
    epic_loop: int              # which round of this epic
    story_id: str
    behavior: str
    before: dict                # summary + list of epic gaps, before the round
    after: dict = field(default_factory=dict)
    cost_usd: float = 0.0
    done: bool = False
    outcome_text: str = ""
    stuck: str = ""             # reviewer's note when the plan is stuck
    d_verified: int = 0
    d_reopened: int = 0
    report_path: Path | None = None

    @property
    def improvement(self) -> int:
        return self.d_verified - self.d_reopened

    def line(self) -> str:
        return (
            f"loop-{self.n} · {self.story_id} fixes {self.behavior} · "
            f"{'DONE' if self.done else 'NOT DONE'} · ${self.cost_usd:.2f} · "
            f"V{self.d_verified:+d} R{self.d_reopened:+d} · epic gaps "
            f"{len(self.before['gaps'])}→{len(self.after.get('gaps', []))}"
        )


@dataclass
class ImproveReport:
    epic: str
    loops: list[Loop] = field(default_factory=list)
    stopped: str = ""
    gaps_left: list[str] = field(default_factory=list)
    error: str = ""
    reconciled: list = field(default_factory=list)
    qualification: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.error and not self.gaps_left and not self.qualification

    @property
    def cost_usd(self) -> float:
        return sum(lo.cost_usd for lo in self.loops)

    def summary(self) -> str:
        if self.error:
            return f"improve {self.epic}: ✗ {self.error}"
        lines = [f"improve {self.epic}: {len(self.loops)} round(s) this run, ${self.cost_usd:.2f}"]
        lines += [f"↺ {r.line()}" for r in self.reconciled]
        lines += [f"  {lo.line()}" for lo in self.loops]
        for lo in self.loops:
            if lo.report_path:
                lines.append(f"  report: {lo.report_path}")
        lines.append(f"⏸ stop: {self.stopped}")
        if self.gaps_left:
            lines.append(f"  {len(self.gaps_left)} epic gap(s) remaining: "
                         + ", ".join(self.gaps_left[:5]))
        return "\n".join(lines)


# ------------------------------------------------------------------ gap


def epic_counts(led: Ledger, epic_id: str) -> dict:
    """VERIFIED/GAP/REOPENED of **behaviors belonging to the epic** -- what the loop targets.

    Global delta (R7) is not used as a stopping condition: the repair story
    itself spawns additional behaviors (`AC-STORY-RP-nn-1`, `qa:fake-tests`)
    and makes delta positive even without closing any gap -- measured on a fake
    client: a round that fixes nothing still gets V+1.
    """
    out = {"epic_verified": 0, "epic_gap": 0, "epic_reopened": 0}
    for b in led.behaviors.values():
        if led.epic_of(b.story) == epic_id:
            out[f"epic_{b.status}"] = out.get(f"epic_{b.status}", 0) + 1
    return out


def epic_gaps(led: Ledger, epic_id: str) -> list[Behavior]:
    """GAP/REOPENED whose owning story belongs to the epic -- REOPENED first, then by id.

    The owning story is the story in the index, not the repair story: behaviors
    of `EPIC-RP-*` (the repair story's own criteria) do not cycle back as new gaps.
    """
    out = [
        b for b in led.behaviors.values()
        if b.status in (GAP, REOPENED) and led.epic_of(b.story) == epic_id
    ]
    return sorted(out, key=lambda b: (b.status != REOPENED, b.id))


#: Behavior kinds entering the auto-repair **queue**, by priority order (decision B6
#: 2026-09-06): criteria with a test id are the most specific verifier; requirements
#: (fr/nfr) proven via the covering story's criteria; screens via visual contract.
#: `qa:*` is **project-level** aggregation (one `aisef qa` run), with no per-story
#: verifier -- outside the queue, handled by `aisef qa --only <kind>`.  Measured B1
#: on e9: rounds 4-5 received `qa:*`, delta -1/-2.
QUEUE_RANK = {"ac": 0, "fr": 1, "nfr": 1, "mockup": 2}

#: What closes each kind of absence (ADR-009 O2).  Three absences were recorded as
#: one GAP and all three got the same paid repair story; only `UNBUILT` is worth
#: one.  `UNTRACED` never enters the queue: the owner decision of 2026-09-06 §4
#: ("a gap that is only missing traceability is fixed by the harness, not by a
#: story") is this dict plus the filter in `repair_queue`.
REPAIR_ACTION = {UNBUILT: "story", UNTESTED: "test-only story", UNTRACED: "harness metadata fix"}


def repair_queue(gaps: list[Behavior]) -> list[Behavior]:
    """Gaps eligible for auto-repair, REOPENED first, then by `QUEUE_RANK`, then id.

    `UNTRACED` is filtered out: the harness has no test name to attach to the
    behaviour, and no amount of agent time buys one — `aisef evidence <id> --link`
    (or a reporter that prints test names) does.  Spending a repair story there
    pays for a metadata edit at story prices.
    """
    return sorted((b for b in gaps if b.kind in QUEUE_RANK and b.gap_kind != UNTRACED),
                  key=lambda b: (b.status != REOPENED, QUEUE_RANK[b.kind], b.id))


# ------------------------------------------------------------------ repair story


def _owner(root: Path, story_id: str) -> Story:
    raw = next((s for s in read_index(root).get("stories", []) if s.get("id") == story_id), {})
    return Story(
        id=story_id, epic_id=str(raw.get("epic_id") or ""), title=str(raw.get("title") or ""),
        acceptance_criteria=list(raw.get("acceptance_criteria") or []),
        covers=list(raw.get("covers") or []), write_scope=list(raw.get("write_scope") or []),
        screens=list(raw.get("screens") or []),
        verification_contract=list(raw.get("verification_contract") or []),
    )


def _describe(b: Behavior, owner: Story) -> str:
    """Acceptance criterion for the repair story = the behavior itself, keeping the
    id so the ledger reconciles.  No backtick-quoting paths here: preflight reads
    this sentence and would demand write permission for any file it sees next to a
    create/modify verb."""
    if b.kind == "ac":
        i = int(b.id.rsplit("-", 1)[1])
        text = owner.acceptance_criteria[i - 1] if 0 < i <= len(owner.acceptance_criteria) \
            else f"criterion {i} of {owner.id}"
        return f"{b.id} green again: {text}"
    if b.kind in ("fr", "nfr"):
        return f"{b.id} green: all criteria of {owner.id} covering this requirement pass"
    if b.kind == "qa":
        return f"{b.id} green: aisef qa --only {b.id.split(':', 1)[1]} passes at HEAD"
    return f"{b.id} green: screen {b.id.split(':', 1)[1]} matches visual contract"


def _contract(b: Behavior, owner: Story) -> tuple[list[str], list[str]]:
    """Verification contract + screens for the repair story, derived from the behavior's source."""
    kinds = verification_contract(owner)
    if b.kind == "qa":
        kind = b.id.split(":", 1)[1]
        if kind in QA_KINDS and kind not in kinds:
            kinds.append(kind)
    screens = [b.id.split(":", 1)[1]] if b.kind == "mockup" else []
    return kinds, screens


def _source_line(b: Behavior) -> str:
    src = b.source or {}
    parts = [f"{k}: `{v}`" for k, v in src.items() if k != "tests" and v]
    return "; ".join(parts) or "(ledger has no source)"


def _body(b: Behavior, owner: Story, story: Story, preservation: list[str], loop: int) -> str:
    ac = f"AC-{story.id}-1"
    out = [
        "",
        "## Fix behavior (improvement loop `loop-%d`, ADR-004 R3)" % loop,
        "",
        f"- Behavior: `{b.id}` — status **{b.status}** in ledger, belongs to {owner.id}"
        + (f" (regression by {b.regressed_by})" if b.regressed_by else ""),
        f"- Absence: **{b.gap_kind}** → {REPAIR_ACTION.get(b.gap_kind, 'story')} (ADR-009 O2)",
        f"- Source: {_source_line(b)}",
        f"- History: `aisef evidence {b.id}`",
        "",
        f"The test proving this behavior must carry **both** this story's tag "
        f"(`{ac}`) **and** the original tag `{b.id}`: the ledger reconciles by the original tag, "
        f"the story gate scores by the new tag. Fix the **project**, not the harness or criteria.",
        "",
        "The test must be **new and tagged**: red when this story's implementation is removed — "
        "the \"does the test check the story\" gate runs a nop control (ADR-005 V3) and scores ✗ "
        "if the test is already green at baseline. Do **not** add tags to existing tests, do not "
        "rename existing tests to carry tags. If this behavior is already fully proven by an "
        "existing test and only lacks a trace tag: **do not change code**, write in the summary "
        "`trace: <test id> — <why sufficient>`; the reviewer returns `[stuck] trace: "
        "<test id>`. The harness handles this as a metadata fix (`aisef evidence "
        f"{b.id} --link \"<test id>\" --why ...`), not as a functional improvement.",
        "",
    ]
    if b.gap_kind == UNTESTED:
        out += [
            "**Test-only story.** The ledger measured the absence of a *test*, not of "
            "the behavior: the write scope is the test paths only, the product code is "
            "out of scope and the scope guard enforces that. Write the tagged test and "
            "stop. If it turns out red — the behavior really is missing — say so in the "
            "summary and leave it red: the ledger then records a red test and the next "
            "round opens a full repair story with the code in scope.",
            "",
        ]
    if preservation:
        out += [
            "## Preservation",
            "",
            "VERIFIED behaviors of other stories within write scope — after the fix "
            "they must still be green (preservation gate, ADR-004 R4):",
            "",
            *[f"- `{bid}`" for bid in preservation],
            "",
        ]
    return "\n".join(out)


def _pick_id(root: Path, state: StateStore, behavior_id: str) -> str:
    """Reuse an unfinished repair story for this same behavior; otherwise new id.
    Avoids creating a duplicate for the same gap each round."""
    stories = read_index(root).get("stories", [])
    recs = state.load().stories
    for s in stories:
        sid = str(s.get("id") or "")
        if s.get("repair_of") == behavior_id and sid in recs \
                and recs[sid].state is not StoryStatus.DONE:
            return sid
    n = 1 + sum(1 for s in stories if str(s.get("id", "")).startswith(STORY_PREFIX))
    return f"{STORY_PREFIX}{n:02d}"


def repair_story(
    led: Ledger,
    b: Behavior,
    *,
    epic_id: str,
    root: Path,
    project: Path,
    config: Config,
    state: StateStore,
    loop: int,
) -> Path:
    """Deterministically generate a repair story for one behavior and register it in the index.

    `write_scope` = owning story's scope + test files required by the verification
    contract (bug 21: requiring tests then forbidding writing them); `depends_on`
    empty; `covers` from the owning story so requirements remain traceable.  The
    repair story goes through the same preflight checks as a regular story (size R5,
    capability, scope) in `run_epic`.
    """
    owner = _owner(root, b.story)
    kinds, screens = _contract(b, owner)
    verify_paths = verification_paths(owner, project, config)
    scope = list(owner.write_scope)
    for p in verify_paths:
        if p not in scope:
            scope.append(p)
    if b.gap_kind == UNTESTED and verify_paths:
        # Test-only story (ADR-009 O2): what the evidence records as missing is the
        # test, not the code, so the scope is the test paths only — the difference
        # between the two actions is enforced by the scope guard, not by prose in
        # the story body.  If the new test comes back red the ledger then records a
        # red test, the gap becomes `unbuilt`, and the next round gets full scope.
        scope = list(verify_paths)
    sid = _pick_id(root, state, b.id)
    story = Story(
        id=sid, epic_id=repair_epic(epic_id),
        title=f"Fix {b.id} ({b.status}) of {owner.id}"[:80],
        acceptance_criteria=[_describe(b, owner)],
        covers=list(owner.covers), write_scope=scope, depends_on=[],
        screens=screens, verification_contract=kinds,
    )
    preservation = complexity.verified_touched(
        story, led.as_dict(), complexity.read_scopes(project))
    return register_story(
        root, story,
        epic_title=f"Fix behavior per ledger — {epic_id}",
        extra={"repair_of": b.id, "loop": f"loop-{loop}", "preservation": preservation,
               "gap_kind": b.gap_kind, "source": dict(b.source or {})},
        body=_body(b, owner, story, preservation, loop),
        wave=[sid],   # one story per round: old failed repair stories don't piggyback
    )


# ------------------------------------------------------------------ loop


def _counts(rec: dict) -> tuple[int, int, int]:
    return int(rec.get("verified", 0)), int(rec.get("gap", 0)), int(rec.get("reopened", 0))


def _epic_rows(led: Ledger, epic_id: str) -> list[dict]:
    """Rounds already run for the epic, with delta of epic behaviors compared to the
    immediately preceding baseline -- that baseline is always the same epic, because
    switching epic creates a new baseline."""
    out, prev = [], None
    for lo in led.loops:
        if lo.get("epic") == epic_id and lo.get("n") != BASELINE and prev is not None:
            out.append({
                **lo,
                "d_verified": int(lo.get("epic_verified", 0)) - int(prev.get("epic_verified", 0)),
                "d_reopened": int(lo.get("epic_reopened", 0)) - int(prev.get("epic_reopened", 0)),
            })
        prev = lo
    return out


def stop_reason(
    led: Ledger,
    epic_id: str,
    gaps: list[Behavior],
    last: Loop | None,
    *,
    max_loops: int,
    flat_loops: int,
    cost_cap: float,
    auto: bool,
    approvals: ApprovalStore,
    outside: list[Behavior] = (),
) -> str:
    """Reason to stop before opening the next round; empty = continue.  All numbers
    read from the ledger.  `gaps` is the **queue** (`repair_queue`); `outside` is
    gaps belonging to the epic but outside the auto-repair queue -- named when
    stopping so nobody reads "no gaps left"."""
    if not gaps:
        # Two different reasons to be outside the queue, two different fixes; one
        # message for both would send the reader to `aisef qa` for a metadata edit.
        untraced = [b for b in outside if b.gap_kind == UNTRACED]
        project = [b for b in outside if b.gap_kind != UNTRACED]
        clauses = []
        if project:
            clauses.append(f"{len(project)} project-level gap(s) outside auto-repair queue: "
                           f"{', '.join(b.id for b in project[:5])} (run `aisef qa`)")
        if untraced:
            why = str((untraced[0].source or {}).get("why") or "")
            clauses.append(
                f"{len(untraced)} gap(s) only missing traceability — harness metadata fix, "
                f"not a repair story: {', '.join(b.id for b in untraced[:5])} "
                + (f"[{why}] " if why else "")
                + f"(`aisef evidence {untraced[0].id} --link \"<test id>\" --why \"…\"`, or "
                "make the runner print test names)")
        if clauses:
            return "no gap with specific verifier remaining in epic — " + "; ".join(clauses)
        return "no GAP/REOPENED remaining in epic"
    if last is not None and last.stuck:
        return f"plan stuck at {last.story_id} — returning to human: {last.stuck}"
    rows = _epic_rows(led, epic_id)
    if len(rows) >= max_loops:
        return f"reached improve.max_loops = {max_loops} ({len(rows)} round(s) ran for epic)"
    tail = rows[-flat_loops:]
    if len(tail) >= flat_loops and all(r["d_verified"] - r["d_reopened"] <= 0 for r in tail):
        return (f"marginal improvement ≤ 0 for {flat_loops} consecutive round(s) "
                f"({', '.join(r['n'] for r in tail)})")
    spent = sum(float(r.get("cost_usd") or 0.0) for r in rows)
    if cost_cap and spent >= cost_cap:
        return f"reached improve.cost_cap_usd = ${cost_cap:.2f} (spent ${spent:.2f})"
    if rows and not auto and approvals.status(Gate.IMPROVE) is not Status.APPROVED:
        return ("awaiting human approval of `improve` gate before round %d: aisef review improve · "
                "aisef approve improve (or --auto)" % (len(rows) + 1))
    return ""


def _qualification_strings(qa, candidate, queue, verdict: QVerdict,
                            *, cfg=None, required=()) -> list[str]:
    """Translate the QA report and the unified verdict into the legacy
    ``report.qualification`` list — same shape, same readers, single
    decision underneath. The legacy surface names every cause; the
    verdict still owns the decision so the two stay consistent."""
    out: list[str] = []
    if not candidate or qa.candidate != candidate:
        out.append("candidate evidence is missing or stale")
    if (cfg is None or cfg.get("verify.clean_tree", True)) and qa.clean_tree != candidate:
        out.append("requested clean-tree evidence unavailable")
    if required and getattr(qa, "waived", None) is not None:
        results = {r.kind.id: r for r in qa.results}
        for kind in sorted(required):
            result = results.get(kind)
            if kind not in qa.waived and (result is None or not result.ran):
                out.append(f"required evidence missing: {kind}")
    product_failures = [r.kind.id for r in qa.failed]
    if qa.fake_tests:
        product_failures.append("fake-tests")
    if product_failures and not queue:
        out.append("product checks failed outside auto-repair queue: "
                   + ", ".join(product_failures))
    for result in qa.unrunnable:
        out.append(f"infrastructure: {result.kind.id}: {result.unrunnable}")
    return out


def _stop_from_verdict(verdict: QVerdict, qualification: list[str]) -> str:
    """Translate the unified verdict into the legacy ``stop`` string. Empty
    when the verdict is "continue" — callers keep the legacy ``stop_reason``
    text in that case so the marginal-improvement rule remains a single
    owner. When the verdict flags evidence/candidate reasons, the joined
    ``report.qualification`` list is the human-readable surface (its lines
    are what dashboards and tests look for); the verdict reason falls back
    when the list is empty (e.g. ``HUMAN`` with no list to project)."""
    if verdict.decision.value in ("repair", "verify", "merge"):
        return ""
    joined = "; ".join(qualification)
    return joined or verdict.reason


#: The reviewer's "only the trace is missing" marker, in both languages the harness
#: itself asks for: `_body` prescribes `[stuck] trace: <test id>` in English while e9
#: reviewers returned `[bế tắc] truy vết: <test id>`.  Matching only one of the two
#: dropped the metadata-fix instruction for the other — the report then read as if the
#: round had simply failed.
_TRACE_STUCK = re.compile(r"truy vết|trace:", re.IGNORECASE)


def _write_report(root: Path, epic_id: str, lo: Loop, decision: str, spent: float) -> Path:
    b, a = lo.before, lo.after
    lines = [
        f"# Improvement loop-{lo.n} — {epic_id} (round {lo.epic_loop} of epic)",
        "",
        f"- Repair story: **{lo.story_id}** — behavior `{lo.behavior}` — "
        f"{'DONE' if lo.done else 'NOT DONE'}",
        f"- Round cost: ${lo.cost_usd:.2f} (repair story evidence) · epic total: ${spent:.2f}",
        f"- Epic behaviors: VERIFIED {b['epic_verified']}→{a['epic_verified']} · "
        f"GAP {b['epic_gap']}→{a['epic_gap']} · REOPENED {b['epic_reopened']}→{a['epic_reopened']} · "
        f"Δverified − Δreopened = {lo.improvement:+d}",
        f"- Project-wide ledger: VERIFIED {b['verified']}→{a['verified']} · GAP {b['gap']}→{a['gap']} · "
        f"REOPENED {b['reopened']}→{a['reopened']}",
        f"- Epic gaps before: {len(b['gaps'])} ({', '.join(b['gaps'][:8]) or '—'})",
        f"- Epic gaps after: {len(a['gaps'])} ({', '.join(a['gaps'][:8]) or '—'})",
        f"- Decision: {'**stop** — ' + decision if decision else '**continue** next round'}",
        *([f"- Metadata fix, **not** a functional improvement: behavior already proven by existing test "
           f"— `aisef evidence {lo.behavior} --link \"<test id>\" "
           f"--why \"...\"` then `aisef report`"]
          if _TRACE_STUCK.search(lo.stuck) else []),
        "",
        "## Gate outcome",
        "",
        "```",
        lo.outcome_text.strip() or "(no stories ran)",
        "```",
        "",
        "To continue: `aisef approve improve` then rerun `aisef improve --epic "
        f"{epic_id}`. History of a behavior: `aisef evidence <id>`.",
        "",
    ]
    path = root / LOOP_REPORT.format(n=lo.n)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def improve(
    project: Path | str,
    client: ClientAdapter,
    epic_id: str,
    *,
    config: Config | None = None,
    max_loops: int = 0,
    auto: bool = False,
    has_ui: bool = True,
) -> ImproveReport:
    try:
        with run_ownership(project):
            return _improve_owned(project, client, epic_id, config=config,
                                  max_loops=max_loops, auto=auto, has_ui=has_ui)
    except RunOwnedError as exc:
        return ImproveReport(epic=epic_id, error=str(exc))


def _improve_owned(
    project: Path | str,
    client: ClientAdapter,
    epic_id: str,
    *,
    config: Config | None = None,
    max_loops: int = 0,
    auto: bool = False,
    has_ui: bool = True,
) -> ImproveReport:
    """Run at most `max_loops` rounds (counting rounds from prior calls too) then exit."""
    project = Path(project)
    root = project / ARTIFACT_ROOT
    cfg = config or Config.load(project)
    max_loops = int(max_loops or cfg["improve.max_loops"])
    flat_loops = int(cfg["improve.flat_loops"])
    cost_cap = float(cfg["improve.cost_cap_usd"])
    report = ImproveReport(epic=epic_id)

    plan = load_plan(root)
    if plan.error:
        report.error = plan.error
        return report
    if epic_id not in plan.waves:
        report.error = f"epic not found in plan: {epic_id}"
        return report
    try:
        worktrees = WorktreeManager(project)
    except GitError as e:
        report.error = f"{e} — repair stories always run in worktree, requires git repo"
        return report

    state = StateStore(root)
    report.reconciled = reconcile_all(artifact_root=root, state=state, worktrees=worktrees)
    approvals = ApprovalStore(root)
    evidence = EvidenceStore(root)

    required = set()
    for raw in read_index(root).get("stories", []):
        if raw.get("epic_id") == epic_id:
            required.update(verification_contract(_owner(root, raw["id"])))

    rounds = JournalStore(root)
    round_id = f"improve-{epic_id}"
    history = rounds.read(round_id)
    intent = history.last("repair.intent")
    closed = history.last("repair.closed")
    pending: Loop | None = None
    for other_id in rounds.story_ids():
        if other_id.startswith("improve-") and other_id != round_id:
            other = rounds.read(other_id)
            opened, finished = other.last("repair.intent"), other.last("repair.closed")
            if opened and (finished is None or finished.seq < opened.seq):
                report.error = f"resume interrupted round for {other_id.removeprefix('improve-')} first"
                return report
    if intent is None:
        recorded = {r.get("story") for r in ledger_mod.build(root).loops}
        orphaned = [s["id"] for s in read_index(root).get("stories", [])
                    if s.get("epic_id") == repair_epic(epic_id) and s.get("repair_of")
                    and s.get("loop") and s["id"] not in recorded]
        if orphaned:
            report.error = "legacy repair round lacks durable attribution; reconcile manually: " + ", ".join(orphaned)
            return report
    if intent is not None and (closed is None or closed.seq < intent.seq):
        data = intent.data
        if data.get("version") != 1:
            report.error = "unsupported repair journal version; manual reconciliation required"
            return report
        pending = Loop(**data["loop"])
        result = history.last("repair.result")
        if result is not None and result.seq > intent.seq:
            for key, value in result.data.items():
                setattr(pending, key, value)
        else:
            pending.cost_usd = max(0.0, evidence.read(pending.story_id).total_cost_usd
                                   - data["cost0"])
            pending.done = rounds.read(pending.story_id).merged()
            pending.stuck = "interrupted repair round; reconciled without automatic redispatch"
            pending.outcome_text = pending.stuck
    while True:
        # Project-level evidence at current HEAD.  One QA run closes the previous
        # round **and** opens the next -- end-to-end QA is expensive, don't run twice.
        label = f"loop-{pending.n}" if pending else BASELINE
        candidate = head_sha(project)
        qa = run_suite(project, config=cfg, has_ui=has_ui, story_id=label,
                       artifact_root=root, candidate=candidate)
        led = ledger_mod.build(root)
        checkpoint = rounds.read("improve-ledger").last("repair.ledger")
        if checkpoint is not None and len(led.loops) < len(checkpoint.data["loops"]):
            led.loops = checkpoint.data["loops"]

        if pending is None:
            last = led.loops[-1] if led.loops else None
            if last is None or last.get("epic") != epic_id \
                    or _counts(last) != _counts(led.summary()):
                led.snapshot(BASELINE).update(epic=epic_id, **epic_counts(led, epic_id))
        else:
            rec = next((r for r in led.loops if r.get("n") == f"loop-{pending.n}"), None)
            if rec is None:
                rec = led.snapshot(f"loop-{pending.n}", cost_usd=pending.cost_usd)
                rec.update(epic=epic_id, story=pending.story_id, behavior=pending.behavior,
                           **epic_counts(led, epic_id),
                           gaps=[b.id for b in epic_gaps(led, epic_id)])
            pending.d_verified = rec["epic_verified"] - pending.before["epic_verified"]
            pending.d_reopened = rec["epic_reopened"] - pending.before["epic_reopened"]
            pending.after = {**rec, "gaps": rec.get("gaps", [])}
        rounds.record("improve-ledger", Entry(step="repair.ledger", data={"loops": led.loops}))
        led.write(root)
        led.index(root)

        gaps = epic_gaps(led, epic_id)
        queue = repair_queue(gaps)
        report.gaps_left = [b.id for b in gaps]

        # Unified qualification policy (phase 2/4): the same rule used by
        # `run` and `pre-deploy` consults this call. ``report.qualification``
        # keeps the legacy list shape for old reports; the verdict itself is
        # the single source of truth. ``stop_reason`` (legacy) still runs so
        # any flat-loop / marginal-improvement conditions the unified rule
        # does not cover stay authoritative.
        q_inputs = QInputs(
            candidate=candidate,
            qa=QQa(
                candidate=qa.candidate,
                clean_tree=qa.clean_tree,
                release_ready=qa.release_ready,
                failed_kinds=tuple(r.kind.id for r in qa.failed),
                unrunnable_kinds=tuple(r.kind.id for r in qa.unrunnable),
                unconfigured_kinds=tuple(r.kind.id for r in qa.unconfigured),
                waived_kinds=tuple(qa.waived),
            ),
            behaviors=tuple(
                # Queue-eligible means exactly what `repair_queue` decided, kind and
                # gap kind together: the unified rule must not see a repairable gap
                # where the queue sees a metadata fix.
                QGap(b.id, b.status, has_verifier=(b in queue))
                for b in gaps),
            approvals=tuple(
                QApproval(g.value, approvals.status(g).value)
                for g in [Gate.IMPROVE]),
            plan_stuck=(pending.stuck if pending is not None else ""),
        )
        spent = sum(float(r.get("cost_usd") or 0.0) for r in _epic_rows(led, epic_id))
        verdict = q_qualify(
            QProfile(
                phase=PHASE_REPAIR,
                max_loops=max_loops,
                cost_cap_usd=cost_cap,
                cost_spent_usd=spent,
                loops_completed=len(_epic_rows(led, epic_id)),
                auto=auto,
                required_kinds=tuple(sorted(required)),
            ),
            q_inputs,
        )
        # Keep the legacy qualification list in sync with the unified rule
        # so old reports and dashboards do not silently lose information.
        report.qualification = _qualification_strings(
            qa, candidate, queue, verdict, cfg=cfg, required=required)
        stop_reason_text = stop_reason(
            led, epic_id, queue, pending, max_loops=max_loops, flat_loops=flat_loops,
            cost_cap=cost_cap, auto=auto, approvals=approvals,
            outside=[b for b in gaps if b not in queue],
        )
        # Whichever source gives the more specific stop wins; tie-breaker is
        # the unified verdict so the new rule has a single owner.  The
        # legacy qualification list still names concrete evidence reasons
        # (clean-tree, missing kind, candidate mismatch) that the verdict
        # reason field summarises; ``if report.qualification`` preserves
        # the same surface callers and tests have asserted on since v1.x.
        if report.qualification:
            stop = "; ".join(report.qualification)
        else:
            stop = stop_reason_text or _stop_from_verdict(verdict, report.qualification)
        if pending is not None:
            pending.report_path = _write_report(root, epic_id, pending, stop, spent)
            report.loops.append(pending)
            rounds.record(round_id, Entry(step="repair.closed", data={"n": pending.n}))
            pending = None
        if stop:
            report.stopped = stop
            return report

        n = 1 + sum(1 for lo in led.loops if lo.get("n") != BASELINE)
        b = queue[0]
        sid = _pick_id(root, state, b.id)
        loop = Loop(n=n, epic_loop=len(_epic_rows(led, epic_id)) + 1, story_id=sid,
                    behavior=b.id,
                    before={**led.summary(), **epic_counts(led, epic_id),
                            "gaps": [g.id for g in gaps]})

        # No changes to `run`/`implement`: the repair story follows the same
        # path as a regular story -- worktree, gate, reviewer != developer.
        cost0 = evidence.read(sid).total_cost_usd
        rounds.record(round_id, Entry(step="repair.intent", data={
            "version": 1, "cost0": cost0,
            "loop": {"n": loop.n, "epic_loop": loop.epic_loop, "story_id": sid,
                     "behavior": loop.behavior, "before": loop.before},
        }))
        path = repair_story(led, b, epic_id=epic_id, root=root, project=project,
                            config=cfg, state=state, loop=n)
        if path.stem != sid:
            raise RuntimeError("repair story identity changed after durable intent")
        rr = RunReport()
        run_epic(
            repair_epic(epic_id), load_plan(root),
            project=project, client=client, config=cfg, state=state,
            worktrees=worktrees, artifact_root=root, report=rr,
        )
        loop.cost_usd = evidence.read(sid).total_cost_usd - cost0
        loop.done = rr.ok
        loop.outcome_text = rr.summary()
        # Two independent models both conclude the repair story is wrong from
        # the plan: the next round with the same gap reaches the same conclusion
        # -- return to human with reviewer's note.
        findings = [f for o in rr.outcomes for a in o.attempts for f in a.review_findings]
        stuck = plan_defects(findings)
        if stuck:
            loop.stuck = next((o.blocked_reason for o in rr.outcomes if o.blocked_reason),
                              "; ".join(stuck))
        rounds.record(round_id, Entry(step="repair.result", data={
            "cost_usd": loop.cost_usd, "done": loop.done,
            "outcome_text": loop.outcome_text, "stuck": loop.stuck,
        }))
        pending = loop
