"""Compile client configuration from a single source of truth.

The framework describes guards **once** (`harness/guardrails.GUARD_MATCHERS`),
then generates configuration for each client.  No maintaining three hand-written
`settings.json` files that easily drift — that is decision D3.

Compilation output is a **generated artifact**, not hand-edited: each file
carries a first line stating this, and the next run overwrites.

The most important thing here is not file generation, but the **loss report**.
When a client cannot wire pre-check guards, compile must say so, so the
operator knows the real assurance level — instead of believing they are
protected (invariant 10).
"""

from __future__ import annotations

import json
import shlex
import sys
from dataclasses import dataclass, field
from pathlib import Path

from ..harness.guardrails import GUARD_MATCHERS
from .base import Capability, ClientAdapter, Support
from .claude_code import ClaudeCodeAdapter
from .opencode import OpenCodeAdapter

GENERATED_NOTE = "Generated by `aisef compile` — do not edit manually, next run will overwrite."

ADAPTERS: dict[str, type[ClientAdapter]] = {
    "claude": ClaudeCodeAdapter,
    "opencode": OpenCodeAdapter,
}


@dataclass
class CompileReport:
    client: str
    written: list[Path] = field(default_factory=list)
    guards_wired: list[str] = field(default_factory=list)
    #: Guards that must be checked after the fact instead of blocking — lower assurance.
    guards_post_hoc: list[str] = field(default_factory=list)
    degradations: list[str] = field(default_factory=list)

    @property
    def blocks_at_source(self) -> bool:
        return not self.guards_post_hoc

    def summary(self) -> str:
        lines = [f"client: {self.client}"]
        if self.client == "opencode":
            # Decision 2026-09-05: second-tier in V1.  Guards block (proven),
            # but cost and turn count are not measurable from the harness.
            lines.append(
                "  second-tier in V1: cost/turns not measurable from harness — "
                "supported, does not block release"
            )
        for p in self.written:
            lines.append(f"  wrote {p}")
        if self.guards_wired:
            # Not all are "pre-check": `diff-scope` runs after each action
            # and `completion` runs when the agent is about to stop.  Lumping
            # them together misreports the assurance level the client provides.
            pre = [g for g in self.guards_wired if GUARD_MATCHERS[g][0] == "PreToolUse"]
            after = [g for g in self.guards_wired if g not in pre]
            if pre:
                lines.append(f"  guards blocking before action: {', '.join(pre)}")
            if after:
                moments = ", ".join(f"{g} ({GUARD_MATCHERS[g][0]})" for g in after)
                lines.append(f"  guards blocking at other hooks: {moments}")
        if self.guards_post_hoc:
            lines.append(f"  ⚠️  guards post-hoc only: {', '.join(self.guards_post_hoc)}")
            lines.append("     — blocking does not occur at write time; `aisef verify` checks later")
        if self.degradations:
            lines.append("  capabilities not at native level:")
            for d in self.degradations:
                lines.append(f"     {d}")
        return "\n".join(lines)


def _guard_command(aisef_bin: str, project: Path, kind: str) -> str:
    if sys.platform == "win32":
        def _q(s: str) -> str:
            return f'"{s}"' if " " in s else s
    else:
        _q = shlex.quote
    return f"{_q(aisef_bin)} --project {_q(str(project))} guard {kind}"


def build_claude_settings(project: Path, aisef_bin: str) -> dict:
    """Build `.claude/settings.json` wiring all guards to the correct hooks."""
    by_event: dict[str, list[dict]] = {}
    for kind, (event, matcher) in sorted(GUARD_MATCHERS.items()):
        by_event.setdefault(event, []).append(
            {
                "matcher": matcher,
                "hooks": [
                    {"type": "command", "command": _guard_command(aisef_bin, project, kind)}
                ],
            }
        )
    return {"_generated": GENERATED_NOTE, "hooks": by_event}


def build_opencode_plugin(project: Path, aisef_bin: str) -> str:
    """Build an OpenCode plugin calling the same guard set.

    Spike S4 has not yet proven whether throwing here **blocks** the tool
    or just logs, so the plugin is still generated but the capability is
    declared as post-hoc.

    Guards are split by hook, not all dumped into one.  `completion` asks
    "are tests green for the current code" — asking that before **every**
    action would block even the first test run, and a guard that blocks
    everything will be removed the same day.  It belongs in `aisef verify`.
    """
    pre = [k for k, (event, _) in sorted(GUARD_MATCHERS.items()) if event == "PreToolUse"]
    post = [k for k, (event, _) in sorted(GUARD_MATCHERS.items()) if event == "PostToolUse"]
    # Claude Code filters tools by this string in `settings.json`;
    # OpenCode has no equivalent mechanism so the plugin must filter itself.
    # Skipping this makes every guard run on every tool: `write-scope` would
    # score even `glob` (arg `path: "."`) then block a **read-only** action,
    # and the agent gets stuck.
    #
    # Match is case-insensitive with anchors: OpenCode tool names are
    # lowercase (`write`, `edit`, `bash`), and without anchors `todowrite`
    # would also match `Write`.
    matchers = "{ " + ", ".join(
        f'"{k}": /^({m})$/i' for k, (_, m) in sorted(GUARD_MATCHERS.items()) if m
    ) + " }"
    return f"""// {GENERATED_NOTE}
import type {{ Plugin }} from "@opencode-ai/plugin"

const BEFORE = [{", ".join(f'"{k}"' for k in pre)}]
const AFTER = [{", ".join(f'"{k}"' for k in post)}]
const MATCH = {matchers}
const BIN = {json.dumps(aisef_bin)}
const PROJECT = {json.dumps(str(project))}

// OpenCode's shell is Bun shell: it **does not** have `.stdin(...)`, it only
// accepts input via redirection from an interpolated value. Getting this wrong
// means every tool call throws TypeError — looks like guard blocking, but the
// guard never actually ran.
async function guard($, kinds, tool, event) {{
  const input = new Blob([event])
  for (const kind of kinds) {{
    if (!MATCH[kind]?.test(tool ?? "")) continue
    const res = await $`${{BIN}} --project ${{PROJECT}} guard ${{kind}} < ${{input}}`
      .quiet().nothrow()
    if (res.exitCode === 2) {{
      throw new Error(String(res.stderr).trim() || `guard ${{kind}} blocked this action`)
    }}
  }}
}}

// `worktree` is the tree the agent is actually standing in — during a story
// run it is .aisef/worktrees/<story>, not PROJECT. If the guard inspects the
// wrong tree it sees all plan files as "out-of-scope changes" and blocks everything.
export const AisefGuardPlugin: Plugin = async ({{ $, directory, worktree }}) => {{
  // `directory` is the session's cwd — matches the `cwd` that Claude Code's
  // hook sends. `worktree` is the git tree root, used only as fallback.
  const CWD = directory || worktree || PROJECT
  return {{
    "tool.execute.before": async (input, output) => {{
      await guard($, BEFORE, input?.tool, JSON.stringify({{
        cwd: CWD,
        tool_name: input?.tool,
        tool_input: output?.args ?? {{}},
      }}))
    }},
    "tool.execute.after": async (input, output) => {{
      await guard($, AFTER, input?.tool, JSON.stringify({{
        cwd: CWD, tool_name: input?.tool, tool_input: {{}},
      }}))
    }},
  }}
}}
"""


def compile_for(
    client: str,
    project: Path | str,
    *,
    aisef_bin: str = "aisef",
) -> CompileReport:
    """Generate one client's configuration, with a loss report."""
    if client not in ADAPTERS:
        raise ValueError(f"client not supported: {client}. Available: {', '.join(sorted(ADAPTERS))}")

    project = Path(project).resolve()
    adapter = ADAPTERS[client]()
    report = CompileReport(client=client, degradations=adapter.degradations())

    blocks = adapter.supports(Capability.PRE_TOOL_GUARD).blocks_at_source
    target = report.guards_wired if blocks else report.guards_post_hoc
    target.extend(sorted(GUARD_MATCHERS))

    if client == "claude":
        path = project / ".claude" / "settings.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(build_claude_settings(project, aisef_bin), indent=2, ensure_ascii=False)
            + "\n",
            encoding="utf-8",
        )
        report.written.append(path)

    elif client == "opencode":
        path = project / ".opencode" / "plugin" / "aisef-guard.ts"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(build_opencode_plugin(project, aisef_bin), encoding="utf-8")
        report.written.append(path)

    return report


def write_compile_report(project: Path | str, reports: list[CompileReport]) -> Path:
    """Write the compile report — the source of truth for the project's real assurance level."""
    project = Path(project)
    path = project / "_bmad-output" / "compile-report.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "clients": [
            {
                "client": r.client,
                "written": [str(p.relative_to(project.resolve())) for p in r.written],
                "guards_wired": r.guards_wired,
                "guards_post_hoc": r.guards_post_hoc,
                "blocks_at_source": r.blocks_at_source,
                "degradations": r.degradations,
            }
            for r in reports
        ]
    }
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return path


def guard_expected(project: Path | str, client_id: str) -> bool:
    """Whether this project **expects** guards to run in this client's sessions.

    The answer lives in `compile-report.json`: if the client's hooks were
    compiled and it declares `blocks_at_source`, every developer session must
    leave at least one guard trace.  Not compiled means no expectation — and
    the gate says "not compiled", not pretending checks ran.
    """
    path = Path(project) / "_bmad-output" / "compile-report.json"
    if not path.is_file():
        return False
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    for c in data.get("clients", []):
        if c.get("client") == client_id:
            return bool(c.get("blocks_at_source"))
    return False
