"""Generate the technical constitution for the target project.

A single source (`kit/rules/*.md`) produces rule files for each client:
`CLAUDE.md` for Claude Code, `AGENTS.md` for OpenCode and other clients
that read that convention. Write once, distribute many -- no maintaining
three copies that drift apart.

Stack-specific sections are appended: Python projects mention `ruff`/`mypy`/
`pytest`, React projects mention `tsc`/`eslint`/`vitest`. Mentioning the
tools the project actually uses ensures agents run the right commands.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .detect_stack import Stack

RULES_DIR = Path(__file__).parent / "rules"

#: Quality-check commands by technology. Only included when the project actually uses it.
QUALITY_COMMANDS: dict[str, list[str]] = {
    "python": ["ruff format --check .", "ruff check .", "mypy .", "pytest --cov"],
    "node": ["npm run lint", "npm run typecheck", "npm test"],
    "go": ["gofmt -l .", "go vet ./...", "go test ./..."],
    "rust": ["cargo fmt --check", "cargo clippy", "cargo test"],
    "java": ["./gradlew check"],
    "dotnet": ["dotnet format --verify-no-changes", "dotnet test"],
    "php": ["composer lint", "composer test"],
    "ruby": ["bundle exec rubocop", "bundle exec rspec"],
    "react": ["npm run lint", "npx tsc --noEmit", "npm test"],
    "vue": ["npm run lint", "npx vue-tsc --noEmit", "npm test"],
    "angular": ["npm run lint", "npm test"],
    "svelte": ["npm run lint", "npm run check", "npm test"],
    "flutter": ["dart format --set-exit-if-changed .", "flutter analyze", "flutter test"],
}

#: Which filename each client reads.
CLIENT_FILES: dict[str, str] = {
    "claude": "CLAUDE.md",
    "opencode": "AGENTS.md",
}


@dataclass
class Constitution:
    principles: str
    must_never: str

    @classmethod
    def load(cls, source_dir: Path = RULES_DIR) -> Constitution:
        return cls(
            principles=(source_dir / "principles.md").read_text(encoding="utf-8"),
            must_never=(source_dir / "must_never.md").read_text(encoding="utf-8"),
        )

    def render(self, project_name: str, stack: Stack) -> str:
        parts = [
            f"# Technical rules — {project_name}",
            "",
            "> Generated by `aisef setup` (AISEF — AI Software Engineering Framework).",
            "> **Do not edit manually** — edit at",
            "> `aisef/kit/rules/` then re-run, otherwise the next install will overwrite.",
            "",
            self.principles.strip(),
            "",
            self.must_never.strip(),
            "",
            self._stack_section(stack),
        ]
        return "\n".join(p for p in parts if p is not None).rstrip() + "\n"

    def _stack_section(self, stack: Stack) -> str:
        lines = ["# This project's technology stack", ""]

        described = {
            k: v for k, v in stack.as_dict().items() if v and k != "undetermined"
        }
        if described:
            for category, values in described.items():
                lines.append(f"- **{category}**: {', '.join(values)}")
        else:
            lines.append("- not determined from `docs/requirements.md`")

        if stack.undetermined:
            lines += [
                "",
                f"Not decided: {', '.join(stack.undetermined)}. The architecture phase decides —",
                "**do not choose** while writing stories.",
            ]

        commands: list[str] = []
        for values in described.values():
            for value in values:
                for cmd in QUALITY_COMMANDS.get(value, []):
                    if cmd not in commands:
                        commands.append(cmd)

        if commands:
            lines += [
                "",
                "## Quality gate",
                "",
                "Run all and must pass before considering a story done:",
                "",
                "```bash",
                *commands,
                "```",
            ]

        if stack.has_ui:
            lines += [
                "",
                "## Stories with UI",
                "",
                "Any story with a `screen_id` must go through both halves of the mockup mapping step:",
                "load the contract slice for that exact screen before writing, and compare",
                "the actual screen against the contract after writing. A missing component that",
                "the contract promised means the story does not pass.",
            ]

        return "\n".join(lines)


def write_for_project(
    project: Path | str,
    project_name: str,
    stack: Stack,
    *,
    clients: list[str] | None = None,
    source_dir: Path = RULES_DIR,
) -> list[Path]:
    """Write rule files for each client. Return list of written paths."""
    constitution = Constitution.load(source_dir)
    text = constitution.render(project_name, stack)

    written = []
    for client in clients or list(CLIENT_FILES):
        filename = CLIENT_FILES.get(client)
        if not filename:
            continue
        path = Path(project) / filename
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written
