"""INV-N.DEFAULT-CAPABILITY on REAL images (SS-65) — no mocks.

For every stack profile in `aisef/harness/capabilities.py`: build (managed) or pull (pinned base) the environment the
registry selects, run every probe, then run the exact AUTO command of every role through the production path
(`tools.run_tool` → sandbox → docker: non-root, all capabilities dropped, no network for security scans) on a clean
fixture project, and require for every capability

    declared == selected == provisioned == probed_successfully == executed

A role the profile leaves empty (Provision.NONE) must resolve to nothing, run nothing and say why. The `init --stack`
presets are probed in their own images with the production preflight probe. Writes
closure-evidence/hardening/tool-capability-matrix.json, which the W0 builder requires for the candidate's product tree.

    python3 validation/tool_capability_qualification.py
"""
from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from aisef.config import DEFAULTS, Config  # noqa: E402
from aisef.harness import capabilities as C  # noqa: E402
from aisef.harness import sandbox, tools, verify_image  # noqa: E402

OUT = ROOT / "closure-evidence/hardening/tool-capability-matrix.json"

FIXTURES: dict[str, dict[str, str]] = {
    "python": {
        "pyproject.toml": '[project]\nname = "calc"\nversion = "0.1.0"\n',
        "calc.py": "def add(a: int, b: int) -> int:\n    return a + b\n",
        "test_calc.py": ("import unittest\n\nfrom calc import add\n\n\nclass TestAdd(unittest.TestCase):\n"
                         "    def test_add(self):\n        self.assertEqual(add(1, 2), 3)\n"),
    },
    "go": {
        "go.mod": "module example.com/calc\n\ngo 1.26\n",
        "calc.go": "// Package calc adds.\npackage calc\n\n// Add returns a+b.\nfunc Add(a, b int) int { return a + b }\n",
        "calc_test.go": ("package calc\n\nimport \"testing\"\n\nfunc TestAdd(t *testing.T) {\n"
                         "\tif Add(1, 2) != 3 {\n\t\tt.Fatal(\"add\")\n\t}\n}\n"),
    },
    "rust": {
        "Cargo.toml": '[package]\nname = "calc"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\n',
        "Cargo.lock": '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "calc"\nversion = "0.1.0"\n',
        "src/lib.rs": ("/// Adds.\npub fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n\n#[cfg(test)]\nmod tests {\n"
                       "    #[test]\n    fn adds() {\n        assert_eq!(super::add(1, 2), 3);\n    }\n}\n"),
    },
    "node": {
        "package.json": json.dumps({"name": "calc", "version": "1.0.0", "private": True,
                                    "scripts": {"test": "node -e \"process.exit(0)\"", "lint": "node -e \"process.exit(0)\""}}, indent=1) + "\n",
    },
    "ruby": {"Gemfile": 'source "https://rubygems.org"\n'},
    "php": {"composer.json": '{"name": "x/calc"}\n'},
    "flutter": {"pubspec.yaml": "name: calc\n"},
}
PRESET_STACK = {"python": "python", "go": "go", "node": "node", "react": "node"}


def git(*a: str) -> str:
    return subprocess.run(["git", "-C", str(ROOT), *a], capture_output=True, text=True, encoding="utf-8").stdout.strip()


def write_fixture(dest: Path, stack: str) -> Path:
    for rel, body in FIXTURES[stack].items():
        f = dest / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(body, encoding="utf-8")
    return dest


def ensure_environment(profile: C.StackProfile, log) -> str:
    image = profile.image
    if profile.managed:
        return verify_image.ensure(image, build=True, log=log)
    ref = profile.base or C.FALLBACK_IMAGE
    if verify_image.present(ref):
        return ""
    p = subprocess.run(["docker", "pull", "-q", ref], capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=900)
    return "" if p.returncode == 0 else f"docker pull {ref} failed: {(p.stderr or p.stdout).strip()[-200:]}"


def run_probe(workspace: Path, image: str, probe: C.Probe) -> dict:
    res = sandbox.run(sandbox.SandboxSpec(workspace=workspace, cmd=list(probe.argv), image=image,
                                          level=sandbox.Level.READ_ONLY, timeout_seconds=120, use_docker=True))
    text = (res.stdout + "\n" + res.stderr).strip()
    first = next((ln.strip() for ln in text.splitlines() if ln.strip()), "")
    ok = res.exit_code == 0 and (not probe.expect or probe.expect in text)
    return {"argv": list(probe.argv), "expect": probe.expect, "exit": res.exit_code, "observed": first[:160], "ok": ok,
            "provider_error": res.provider_error}


def qualify_profile(profile: C.StackProfile, work: Path, log) -> dict:
    fixture = write_fixture(work / profile.stack, profile.stack)
    cfg = Config(dict(DEFAULTS))
    t0 = time.time()
    env_err = ensure_environment(profile, log)
    image = profile.image
    rec = {"stack": profile.stack, "markers": list(profile.markers), "base": profile.base or C.FALLBACK_IMAGE,
           "managed": profile.managed, "image": image, "image_id": verify_image.image_id(image) if not env_err else "",
           "recipe_digest": profile.digest if profile.managed else "", "dockerfile": profile.dockerfile() if profile.managed else "",
           "environment_error": env_err, "environment_seconds": round(time.time() - t0, 1),
           "runtime": [run_probe(fixture, image, pr) for pr in profile.runtime] if not env_err else [], "roles": {}}
    rows = {r.role: r for r in C.resolve(fixture, cfg)}
    checks = {c.key: c for c in verify_image.check_tools(fixture, cfg, build=False)} if not env_err else {}
    runtime_ok = all(p["ok"] for p in rec["runtime"])
    for role in C.Role:
        cap, row = profile.capability(role), rows[role]
        role_rec = {"tool_id": cap.tool_id, "command": cap.command, "provision": cap.provision.value, "version": cap.version,
                    "version_policy": cap.version_policy, "evidence": cap.evidence, "required": cap.required, "note": cap.note,
                    "resolved_mode": row.mode.value, "resolved_command": row.command, "declared": True}
        role_rec["selected"] = (row.mode is C.Mode.AUTO and row.capability == cap
                                and row.command == (cap.command if cap.provision is not C.Provision.NONE else ""))
        if cap.provision is C.Provision.NONE:
            res = tools.run_tool(role.value, fixture, config=cfg)
            role_rec.update(provisioned=None, probe_state="n/a", executed=None,
                            exec={"skipped": res.skipped, "ran": res.ran},
                            status="NONE_DECLARED" if role_rec["selected"] and not res.ran and cap.note in res.skipped else "FAIL")
            rec["roles"][role.value] = role_rec
            continue
        if cap.provision is C.Provision.MANAGED:
            rendered = profile.dockerfile()
            provisioned = not env_err and all(s.partition(":")[2].split("=")[0].split("@")[0] in rendered for s in cap.install)
        elif cap.provision is C.Provision.TOOLCHAIN:
            provisioned = not env_err and "@sha256:" in profile.base
        else:
            provisioned = not env_err and runtime_ok
        check = checks.get(row.key)
        role_rec.update(provisioned=provisioned, probe_state=check.state if check else "not probed",
                        probe_observed=check.observed if check else "", probe_detail=check.detail if check else "")
        started = time.time()
        res = tools.run_tool(role.value, fixture, config=cfg) if not env_err else None
        role_rec["exec"] = ({"exit": res.exit_code, "ok": res.ok, "unrunnable": res.unrunnable, "skipped": res.skipped,
                             "outcome": tools.outcome_kind(res), "seconds": round(time.time() - started, 1),
                             "tail": res.tail(6)} if res else {"error": env_err})
        role_rec["executed"] = bool(res and res.ok and res.exit_code == 0 and not res.unrunnable and not res.skipped)
        role_rec["status"] = ("QUALIFIED" if all([role_rec["selected"], provisioned, role_rec["probe_state"] == "present",
                                                 role_rec["executed"]]) else "FAIL")
        rec["roles"][role.value] = role_rec
    rec["status"] = "FAIL" if env_err or any(r["status"] == "FAIL" for r in rec["roles"].values()) or not runtime_ok else "QUALIFIED"
    return rec


def qualify_presets(work: Path) -> list[dict]:
    from aisef.cli.harness import STACK_PRESETS
    out = []
    for name, preset in STACK_PRESETS.items():
        fixture = write_fixture(work / f"preset-{name}", PRESET_STACK[name])
        cfg = Config(dict(DEFAULTS)).overlay(preset)
        checks = verify_image.check_tools(fixture, cfg, build=True)
        rows = [{"key": c.key, "command": c.command, "state": c.state, "mode": c.mode, "observed": c.observed,
                 "detail": c.detail} for c in checks]
        # A project-local runner (npx / npm) is UNJUDGED by construction: its tool is the project's dependency.
        bad = [r for r in rows if not (r["state"] == "present" or (r["state"] == "UNJUDGED"
                                                                  and r["command"].split()[0] in ("npx", "npm")))]
        out.append({"preset": name, "image": preset["sandbox.image"], "checks": rows,
                    "status": "FAIL" if bad else "QUALIFIED", "failures": bad})
    return out


def main() -> int:
    t0 = time.time()
    dirty = git("status", "--porcelain", "--", "aisef").splitlines()
    log = lambda m: print(f"  … {m}", flush=True)  # noqa: E731
    with tempfile.TemporaryDirectory(prefix="aisef-capqual-") as td:
        work = Path(td)
        profiles = []
        for p in C.PROFILES:
            print(f"== {p.stack} ({p.image})", flush=True)
            rec = qualify_profile(p, work, log)
            print(f"   {rec['status']}: " + ", ".join(f"{k}={v['status']}" for k, v in rec["roles"].items()), flush=True)
            profiles.append(rec)
        presets = qualify_presets(work)
        for pr in presets:
            print(f"== preset {pr['preset']}: {pr['status']}", flush=True)
    caps = [(p["stack"], k, v) for p in profiles for k, v in p["roles"].items()]
    totals = {"profiles": len(profiles), "capabilities": len(caps),
              "qualified": sum(1 for *_, v in caps if v["status"] == "QUALIFIED"),
              "none_declared": sum(1 for *_, v in caps if v["status"] == "NONE_DECLARED"),
              "failed": [f"{s}.{k}" for s, k, v in caps if v["status"] == "FAIL"]
                        + [f"{p['stack']} environment/runtime" for p in profiles if p["status"] == "FAIL" and not any(v["status"] == "FAIL" for v in p["roles"].values())],
              "presets_failed": [p["preset"] for p in presets if p["status"] == "FAIL"]}
    registry = (ROOT / "aisef/harness/capabilities.py").read_bytes()
    out = {"generated": time.strftime("%Y-%m-%dT%H:%M:%S%z"), "invariant": "INV-N.DEFAULT-CAPABILITY",
           "rule": "AUTO_SELECTED(tool, stack, profile) => AVAILABLE(tool, resolved_environment); for every capability "
                   "declared == selected == provisioned == probed_successfully == executed (real images, production path, no mocks)",
           "git_sha": git("rev-parse", "HEAD"), "aisef_tree": "" if dirty else git("rev-parse", "HEAD:aisef"),
           "aisef_dirty": dirty, "registry_sha256": hashlib.sha256(registry).hexdigest(),
           "docker": subprocess.run(["docker", "version", "--format", "{{.Server.Version}} {{.Server.Arch}}"],
                                    capture_output=True, text=True, encoding="utf-8").stdout.strip(),
           "profiles": profiles, "presets": presets, "totals": totals, "elapsed_s": round(time.time() - t0, 1)}
    out["pass"] = not dirty and not totals["failed"] and not totals["presets_failed"]
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(json.dumps(totals), "| pass", out["pass"], "| aisef dirty", bool(dirty), f"| {out['elapsed_s']}s")
    return 0 if out["pass"] else 1


if __name__ == "__main__":
    shutil.which("docker") or sys.exit("docker is required: this qualification runs real images")
    sys.exit(main())
