"""Human approval gate (Human-In-The-Loop).

Design principle: **approval is on-disk state, not an interactive prompt.**
This is what makes the same mechanism work everywhere:

* background / CI — no one sits at a screen to answer;
* in a chat session (Claude Desktop) — the agent cannot "wait" for user input;
* the approver may be a different person, at a different time, on a different machine.

Flow: pipeline reaches gate -> writes ``pending`` and **stops** -> user runs
``approve``/``reject`` -> re-running the pipeline continues from there.

Two key guarantees:

1. **Approval binds to content, not to gate name.** The record stores the
   SHA-256 of the artifact. Editing the artifact after approval invalidates it.
2. **Editing an upstream layer invalidates downstream layers.** Editing the PRD
   makes approved Architecture, UX, Epics, Stories, Mockups all ``stale`` —
   because they were approved against a PRD version that no longer exists.
"""

from __future__ import annotations

import hashlib
import json
import os
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path

#: Normalized story index — produced by the story splitter (phase 4.3).
STORIES_INDEX = "stories.index.json"

#: Pre-deploy gate check result — what the approver reads before signing off.
PRE_DEPLOY_REPORT = "pre-deploy-report.json"


class Gate(str, Enum):
    """Gates requiring human approval, in lifecycle order."""

    PRD = "prd"
    ARCHITECTURE = "architecture"
    UX_SPEC = "ux-spec"
    EPICS = "epics"
    STORIES = "stories"
    MOCKUPS = "mockups"
    READINESS = "readiness"        # lock before starting implementation
    PRE_DEPLOY = "pre-deploy"      # lock before deployment
    #: Gate for the epic improvement loop (ADR-004 R3): approve **continuing**
    #: to round >= 2 after reading the report from the just-finished round.
    #: Intentionally **not** in `GATE_ORDER`: it is not a lifecycle layer —
    #: a project that never ran `improve` must not get stuck at `pre-deploy`
    #: because of it, and it repeats each round rather than being approved once.
    IMPROVE = "improve"


#: Lifecycle order. Re-approving a gate makes all downstream gates stale.
GATE_ORDER: tuple[Gate, ...] = (
    Gate.PRD,
    Gate.ARCHITECTURE,
    Gate.UX_SPEC,
    Gate.EPICS,
    Gate.STORIES,
    Gate.MOCKUPS,
    Gate.READINESS,
    Gate.PRE_DEPLOY,
)

#: Artifact(s) for each gate, relative to artifact root.
#:
#: Names must match **actual files on disk**, because approval binds to a
#: content hash: a wrong name yields an empty hash and the gate never detects
#: changes — a gate that looks harmless from outside but protects nothing.
#:
#: The UX gate has two files because BMAD produces two role-separated documents
#: (`DESIGN.md` is the visual system, `EXPERIENCE.md` is flows and screens).
#: Approving one file then editing the other would slip through.
GATE_ARTIFACTS: dict[Gate, tuple[str, ...]] = {
    Gate.PRD: ("prd.md",),
    Gate.ARCHITECTURE: ("architecture.md",),
    Gate.UX_SPEC: ("DESIGN.md", "EXPERIENCE.md"),
    Gate.EPICS: ("epics.md",),
    Gate.STORIES: (STORIES_INDEX,),
    Gate.MOCKUPS: ("design-contract.json",),
    # The last two gates are **not** bound to `sprint-status.json`: that file
    # changes after every story, so approval would immediately become `stale`
    # — turning the gate into constant noise that gets ignored.
    Gate.READINESS: (STORIES_INDEX, "design-contract.json"),
    Gate.PRE_DEPLOY: (PRE_DEPLOY_REPORT,),
    # Glob pattern: one report per round, number of rounds unknown in advance.
    # Combined hash covers **all** reports, so a new round makes the old
    # approval `stale` — the human must read the new report before approving
    # the next round.
    Gate.IMPROVE: ("LOOP-REPORT-*.md",),
}


class Status(str, Enum):
    PENDING = "pending"                    # awaiting human review
    APPROVED = "approved"                  # approved, content unchanged
    CHANGES_REQUESTED = "changes_requested"  # returned with notes
    STALE = "stale"                        # was approved but content has changed


AUTO_APPROVER = "auto"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _current_user() -> str:
    return os.environ.get("AISEF_APPROVER") or os.environ.get("USER") or "unknown"


#: Story/epic prefix generated by the improvement loop (ADR-004 R3).
REPAIR_PREFIX = ("STORY-RP-", "EPIC-RP-")


def is_present(path: Path) -> bool:
    """Does this artifact exist — false, never an exception, for a path that
    cannot exist.

    `artifact_paths` deliberately returns the unmatched **pattern** so a
    message can name what is missing (`LOOP-REPORT-*.md`). On POSIX asking
    `is_file()` about that just answers False; on Windows `*` is an illegal
    filename character and `stat` raises `OSError [Errno 22]`. 22 of the 48
    failures in the first Windows CI run were this one call.
    """
    try:
        return path.is_file()
    except OSError:
        return False


def _artifact_hash(path: Path) -> str:
    """Hash a gate artifact; for `stories.index.json` specifically, hash
    **normalized content with repair stories excluded**, not raw bytes.

    Repair stories are generated by `aisef improve` and managed by the human
    `improve` gate. Including them in the hash would make the
    `stories`/`readiness` gates stale after every improvement round, and the
    next `improve` call would be blocked by its own predecessor (measured on
    e9 2026-09-06 05:44). Normalization (sorted keys, whitespace-independent)
    ensures that rewriting the same content does not trigger staleness. Changing
    the hash method makes previously signed `stories`/`readiness` approvals
    stale **once** — stated here instead of leaving the user to guess. Falls
    back to raw byte hashing if JSON cannot be parsed.
    """
    if path.name != STORIES_INDEX or not path.is_file():
        return sha256_of(path)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return sha256_of(path)
    if not isinstance(data, dict):
        return sha256_of(path)
    loc = dict(data)
    for key in ("stories", "epics"):
        if isinstance(loc.get(key), list):
            loc[key] = [x for x in loc[key]
                        if not (isinstance(x, dict) and str(x.get("id", "")).startswith(REPAIR_PREFIX))]
    # Repair epic waves also change each round (`register_story(wave=[sid])`):
    # bug 28, e9 2026-09-06 06:50 — rounds 4/5 made `stories`/`readiness`
    # stale again despite bug 25 already filtering stories/epics. Same prefix
    # filter, same rationale.
    if isinstance(loc.get("waves"), dict):
        loc["waves"] = {k: v for k, v in loc["waves"].items() if not str(k).startswith(REPAIR_PREFIX)}
    return hashlib.sha256(json.dumps(loc, ensure_ascii=False, sort_keys=True).encode()).hexdigest()


def _repair_slice_hash(path: Path) -> str:
    """Digest of exactly what `_artifact_hash` removes from the stories index — repair stories, repair epics and
    repair waves — so that every repair story is inside SOME approval's digest (the `improve` gate's; SS-54)."""
    if not path.is_file():
        return ""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return ""
    if not isinstance(data, dict):
        return ""
    lat = {key: [x for x in data.get(key) or [] if isinstance(x, dict) and str(x.get("id", "")).startswith(REPAIR_PREFIX)]
           for key in ("stories", "epics")}
    waves = data.get("waves") if isinstance(data.get("waves"), dict) else {}
    lat["waves"] = {k: v for k, v in waves.items() if str(k).startswith(REPAIR_PREFIX)}
    return hashlib.sha256(json.dumps(lat, ensure_ascii=False, sort_keys=True).encode()).hexdigest()


def _verifier_config_digest(root: Path) -> str:
    """The digest F1 stamps on every verdict (tools.*, verify.*, coverage.*, security.*, review.*), read from the
    project's declared configuration — the artifact root's parent, file-based only: an environment override is the
    operator's session and is already part of each verdict's identity (SS-55)."""
    from ..config import Config
    from .identity import verifier_config_digest
    try:
        return verifier_config_digest(Config.load(root.parent, env={}))
    except Exception:  # noqa: BLE001 — an unreadable config is "no declared config", hashed as such, never a crash here
        return ""


def sha256_of(path: Path) -> str:
    """Hash artifact content. Returns empty string if the file does not exist."""
    if not path.is_file():
        return ""
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


@dataclass
class Approval:
    """A single approval decision, with an audit trail."""

    gate: str
    artifact: str
    artifact_sha256: str
    status: str
    #: Monotonic sequence number within the store. Used to order decisions
    #: instead of ``decided_at``: records may be created on different machines
    #: (via git), so clocks are unreliable, and two decisions in the same
    #: second are indistinguishable by timestamp.
    seq: int = 0
    decided_by: str = ""
    decided_at: str = ""  # informational only, not used for ordering
    note: str = ""
    machine_checks: dict[str, str] = field(default_factory=dict)
    history: list[dict[str, str]] = field(default_factory=list)

    @property
    def was_auto(self) -> bool:
        return self.decided_by == AUTO_APPROVER


class ApprovalStore:
    """Read/write approval records under ``<artifact_root>/approvals/``."""

    def __init__(self, artifact_root: Path):
        self.root = Path(artifact_root)
        self.dir = self.root / "approvals"

    def _path(self, gate: Gate) -> Path:
        return self.dir / f"{gate.value}.json"

    def artifact_paths(self, gate: Gate) -> list[Path]:
        out: list[Path] = []
        for name in GATE_ARTIFACTS[gate]:
            # If the glob matches nothing, return the pattern itself so
            # "missing" can name the file instead of being silent.
            matched = sorted(self.root.glob(name)) if any(c in name for c in "*?[") else []
            out += matched or [self.root / name]
        return out

    def artifact_path(self, gate: Gate) -> Path:
        """Primary file of the gate — used for display."""
        return self.artifact_paths(gate)[0]

    def has_artifacts(self, gate: Gate) -> bool:
        """Whether **all** files for this gate exist."""
        return all(is_present(p) for p in self.artifact_paths(gate))

    def content_hash(self, gate: Gate) -> str:
        """Combined hash of all gate files, in declaration order — plus what the gate covers beyond its files:
        readiness covers the verifier configuration (SS-55), improve covers the repair slice of the stories index
        that `stories`/`readiness` deliberately leave out (SS-54). INV-P.1: the digest is what a person approved."""
        parts = [f"{p.relative_to(self.root)}:{_artifact_hash(p)}" for p in self.artifact_paths(gate)]
        if gate is Gate.READINESS:
            parts.append(f"verifier-config:{_verifier_config_digest(self.root)}")
        if gate is Gate.IMPROVE:
            parts.append(f"repair-stories:{_repair_slice_hash(self.root / STORIES_INDEX)}")
        return hashlib.sha256("\n".join(parts).encode()).hexdigest()

    def load(self, gate: Gate) -> Approval | None:
        p = self._path(gate)
        if not p.is_file():
            return None
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return None
        return Approval(**data)

    def save(self, approval: Approval) -> None:
        self.dir.mkdir(parents=True, exist_ok=True)
        path = self._path(Gate(approval.gate))
        tmp = path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(asdict(approval), indent=2, ensure_ascii=False), encoding="utf-8")
        tmp.replace(path)  # atomic write — no corrupt file on interruption

    # ------------------------------------------------------------ queries

    def status(self, gate: Gate) -> Status:
        """Current effective status of a gate.

        Recomputed from actual on-disk content, so an artifact edited after
        approval is automatically revealed as ``stale`` without anyone marking it.
        """
        rec = self.load(gate)
        if rec is None:
            return Status.PENDING
        if rec.status == Status.CHANGES_REQUESTED.value:
            return Status.CHANGES_REQUESTED
        if rec.status != Status.APPROVED.value:
            return Status.PENDING

        if self.content_hash(gate) != rec.artifact_sha256:
            return Status.STALE  # content changed since approval
        if self._upstream_decided_after(gate, rec.seq):
            return Status.STALE  # an upstream gate was re-decided after this one
        if self._upstream_stale(gate):
            return Status.STALE  # an upstream artifact was edited after its approval (SS-56): content cascades too
        return Status.APPROVED

    def _upstream_stale(self, gate: Gate) -> bool:
        """True if any upstream gate's own status is STALE — a content edit, not only a later decision."""
        if gate not in GATE_ORDER:
            return False
        idx = GATE_ORDER.index(gate)   # ponytail: recomputes upstream hashes per call; memoise if `status` shows up in a profile
        return any(self.status(up) is Status.STALE for up in GATE_ORDER[:idx])

    def _upstream_decided_after(self, gate: Gate, seq: int) -> bool:
        """True if any upstream gate was decided after this gate."""
        if gate not in GATE_ORDER:
            return False  # gates outside the lifecycle (`improve`) have no upstream
        idx = GATE_ORDER.index(gate)
        return any(
            (rec := self.load(up)) is not None and rec.seq > seq
            for up in GATE_ORDER[:idx]
        )

    def _next_seq(self) -> int:
        """Next sequence number within the store."""
        highest = 0
        for g in Gate:
            rec = self.load(g)
            if rec:
                highest = max(highest, rec.seq)
        return highest + 1

    def blocking(self, gate: Gate) -> list[Gate]:
        """Gates that must be resolved before `gate` is allowed to proceed."""
        if gate not in GATE_ORDER:
            return []
        idx = GATE_ORDER.index(gate)
        return [g for g in GATE_ORDER[:idx] if self.status(g) is not Status.APPROVED]

    def summary(self) -> list[tuple[Gate, Status, str]]:
        out = []
        for g in GATE_ORDER:
            rec = self.load(g)
            out.append((g, self.status(g), rec.decided_by if rec else ""))
        return out

    # ------------------------------------------------------------ decisions

    def decide(
        self,
        gate: Gate,
        status: Status,
        *,
        by: str = "",
        note: str = "",
        machine_checks: dict[str, str] | None = None,
    ) -> Approval:
        """Record a decision, preserving the full prior history."""
        prev = self.load(gate)
        history = list(prev.history) if prev else []
        if prev:
            history.append({
                "status": prev.status,
                "decided_by": prev.decided_by,
                "decided_at": prev.decided_at,
                "note": prev.note,
                "artifact_sha256": prev.artifact_sha256,
            })

        rec = Approval(
            gate=gate.value,
            artifact=", ".join(GATE_ARTIFACTS[gate]),
            artifact_sha256=self.content_hash(gate),
            status=status.value,
            seq=self._next_seq(),
            decided_by=by or _current_user(),
            decided_at=_now(),
            note=note,
            machine_checks=machine_checks or (prev.machine_checks if prev else {}),
            history=history,
        )
        self.save(rec)
        return rec

    def approve(self, gate: Gate, *, by: str = "", note: str = "") -> Approval:
        return self.decide(gate, Status.APPROVED, by=by, note=note)

    def reject(self, gate: Gate, *, note: str, by: str = "") -> Approval:
        if not note.strip():
            raise ValueError("rejection must include a note explaining what to fix")
        return self.decide(gate, Status.CHANGES_REQUESTED, by=by, note=note)

    def auto_approve(self, gate: Gate, *, reason: str = "--auto-approve") -> Approval:
        """Machine approval. Always records ``decided_by=auto`` so it is
        possible to later identify which artifacts were never reviewed by a
        human."""
        return self.decide(gate, Status.APPROVED, by=AUTO_APPROVER, note=reason)


def parse_auto_approve(value: str | None) -> frozenset[Gate]:
    """Parse the ``--auto-approve`` argument.

    ``None``/empty -> no gates; ``all`` -> all gates; or a comma-separated
    list of gate names (``prd,architecture``).
    """
    if not value:
        return frozenset()
    raw = value.strip().lower()
    if raw == "all":
        return frozenset(GATE_ORDER)

    gates, unknown = set(), []
    for part in (p.strip() for p in raw.split(",")):
        if not part:
            continue
        try:
            gates.add(Gate(part))
        except ValueError:
            unknown.append(part)
    if unknown:
        valid = ", ".join(g.value for g in GATE_ORDER)
        raise ValueError(f"invalid gate: {', '.join(unknown)}. Valid: {valid}")
    return frozenset(gates)
