"""Convert BMAD documents to structured data.

This is the **boundary that keeps BMAD as a dependency, not a foundation**
(decision D4). The framework owns its own data model; BMAD produces
markdown, this module translates it into that model. Switching from BMAD to
another tool only requires a new translator; orchestration and gates are
untouched.

Document shape observed from real PRDs generated by BMAD (spike S6, fixture
`tests/fixtures/bmad/prd.md`), not guessed:

* functional requirements: ``#### FR-1: Title`` then description, then a
  ``**Consequences (testable):**`` section — which are the acceptance
  criteria, already in verifiable form;
* non-functional requirements: ``- **NFR-1 — Title.** description``;
* assumptions: marked ``[ASSUMPTION: ...]`` inline where they arise;
* open questions: ``OQ-n``, with affected scope when present.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from .experience import slugify

#: `#### FR-1: Create note`
_FR_HEADING = re.compile(
    r"^#{2,5}\s+(FR-\d+)\s*[:：—–-]\s*(.+?)\s*$", re.MULTILINE | re.IGNORECASE
)

#: `- **NFR-1 — App launch time.** From the moment...`
_NFR_ITEM = re.compile(
    r"^(?:[-*]\s+\*\*(NFR-\d+)\s*[:：—–-]\s*(.+?)\.?\*\*\s*(.*)"
    r"|#{2,5}\s+\*{0,2}(NFR-\d+)\s*[:：—–-]\s*(.+?)\s*\*{0,2})$",
    re.MULTILINE | re.IGNORECASE,
)
#: Section heading for NFR block — Vietnamese or English.
#: Used as fallback: auto-number unlabelled bullets when the heading is present
#: but the agent omitted NFR-N IDs.
_NFR_SECTION = re.compile(
    r"^#{2,5}\s+.*(?:Yêu cầu phi chức năng|Non-?functional\s+Requirements?)"
    r"\s*$",
    re.MULTILINE | re.IGNORECASE,
)
_PLAIN_BULLET = re.compile(r"^(?:[-*]|\d+[.):])\s+(.+?)\s*$", re.MULTILINE)

#: Criteria block heading — agent writes in English or Vietnamese depending on
#: the run (bug 19, 2026-09-05: second `plan` run wrote Vietnamese heading and
#: PRD gate dropped all 14 FRs because parser only knew "Consequences (testable)").
_CONSEQUENCES_HEAD = (
    r"(?:Consequences\s*\(testable\)"
    r"|(?:Testable|Verifiable|Acceptance|Verification|Test)\s+(?:criteria|consequences|conditions)"
    r"|Criteria"
    r"|Hệ quả(?:\s+kiểm chứng(?:\s+được)?|\s*\([^)]*\))?"
    r"|Tiêu chí(?:\s+(?:kiểm chứng(?:\s+được)?|chấp nhận|xác nhận|nghiệm thu|kiểm tra))?"
    r")"
)
_CONSEQUENCES = re.compile(
    r"(?:\*\*" + _CONSEQUENCES_HEAD + r"\s*[:：]?\*\*"
    r"|#{2,5}\s+" + _CONSEQUENCES_HEAD + r")"
    r"\s*[:：]?\s*\n(.*?)(?=\n#{2,5}\s|\n\*\*|\Z)",
    re.IGNORECASE | re.DOTALL,
)
_BULLET = re.compile(r"^(?:[-*]|\d+[.):])\s+(.+?)\s*$", re.MULTILINE)

_ASSUMPTION = re.compile(r"\[ASSUMPTION:\s*(.+?)\]", re.DOTALL | re.IGNORECASE)
_OQ_MENTION = re.compile(r"\b(OQ-\d+)\b")
#: `**OQ-1 (blocks FR-13..FR-15)** — ...` or `- **OQ-1:** ...`
_OQ_DEFINITION = re.compile(
    r"(?:\*\*(OQ-\d+)\s*(?:\(([^)]*)\))?\s*[:：]?\s*\*\*\s*[—–:：-]?\s*(.+?)"
    r"|#{2,5}\s+(OQ-\d+)\s*(?:\(([^)]*)\))?\s*[:：—–-]\s*(.+?))"
    r"(?=\n[-*]\s+\*\*OQ-|\n\d+\.\s+\*\*OQ-|\n#{2,5}\s+OQ-|\n\d+\.\s|\n\n|\Z)",
    re.DOTALL | re.IGNORECASE,
)
#: Section heading for assumptions — used as fallback when inline
#: `[ASSUMPTION: ...]` markers are absent.
_ASSUMPTION_SECTION = re.compile(
    r"^#{2,5}\s+.*(?:Assumptions|Giả định)\s*$",
    re.MULTILINE | re.IGNORECASE,
)
_SECTION_ASSUMPTION_ITEM = re.compile(
    r"^[-*]\s+(?:\*\*[^*]+\*\*\s*[:：]?\s*)?(.+?)\s*$",
    re.MULTILINE,
)
_FR_RANGE = re.compile(r"FR-(\d+)\s*\.\.\s*FR-(\d+)")
_FR_SINGLE = re.compile(r"\bFR-(\d+)\b")


@dataclass
class Requirement:
    id: str
    kind: str  # "functional" | "non_functional"
    title: str
    description: str = ""
    #: Testable consequences — used directly as story acceptance criteria.
    acceptance_criteria: list[str] = field(default_factory=list)
    open_questions: list[str] = field(default_factory=list)

    @property
    def is_testable(self) -> bool:
        """A requirement without testable criteria cannot be accepted."""
        return bool(self.acceptance_criteria)


@dataclass
class OpenQuestion:
    id: str
    text: str
    #: Requirements blocked until this question is answered.
    blocks: list[str] = field(default_factory=list)


#: Lockfiles follow their manifest. Package managers write lockfiles as a
#: **consequence** of any dependency change — declaring the manifest without
#: the lockfile is declaring half of an indivisible pair.
#:
#: Measured on e9: AC 1 of STORY-01-01 required "lockfile is committed", but
#: `write_scope` only had `package.json`. Guard blocked lockfile write, agent
#: followed instructions — reverted it and reported missing scope — reviewer
#: blocked correctly because AC 1 failed, and the retry loop ran 4 identical
#: times, $9.85 for a deadlock with no way out.
#: Dependency manifest files. Any story may need to add a package — blocking
#: it creates a deadlock that burns the entire retry budget before surfacing.
MANIFESTS = (
    "package.json", "pyproject.toml", "requirements.txt", "requirements.in",
    "Cargo.toml", "go.mod", "Gemfile", "composer.json",
)

LOCKFILES: dict[str, tuple[str, ...]] = {
    "package.json": ("package-lock.json", "pnpm-lock.yaml", "yarn.lock", "bun.lockb"),
    "pyproject.toml": ("poetry.lock", "uv.lock", "pdm.lock"),
    "requirements.in": ("requirements.txt",),
    "Cargo.toml": ("Cargo.lock",),
    "go.mod": ("go.sum",),
    "Gemfile": ("Gemfile.lock",),
    "composer.json": ("composer.lock",),
}


def effective_write_scope(story: Story, project: Path) -> list[str]:
    """Effective write scope: story-declared scope plus dependency manifests.

    BMAD lists source files in ``write_scope``; it does not anticipate that
    the story will need to declare a package. But acceptance criteria do —
    "test on ``fake-indexeddb``", "lockfile is committed" — and then the
    story cannot satisfy its own criteria. Measured on e9: two consecutive
    stories deadlocked for this reason, $20 for eight attempts with none
    passing.

    Only add files that **actually exist** in the project: adding blindly
    widens scope without changing anything, and the scope list printed for
    the agent gains meaningless lines.

    Deliberately does **not** touch the scope the scheduler uses for wave
    splitting: the question there is different — whether two stories
    overlap — and including manifests would make every story overlap,
    killing parallel execution.
    """
    scope = list(story.write_scope)
    for name in MANIFESTS:
        if name not in scope and (project / name).is_file():
            scope.append(name)
    for path in verification_paths(story, project):
        if path not in scope:
            scope.append(path)
    return with_lockfiles(scope)


#: Verification kind -> config key holding the command to run it.
_VERIFY_COMMAND_KEY = {"unit": "tools.test"}


_JS_CONFIGS = {
    "playwright": ("playwright.config.js", "playwright.config.ts"),
    "jest": ("jest.config.js", "jest.config.ts", "jest.config.mjs"),
    "vitest": ("vitest.config.js", "vitest.config.ts", "vitest.config.mts"),
    "cypress": ("cypress.config.js", "cypress.config.ts"),
    "mocha": (".mocharc.yml", ".mocharc.json"),
}
_PY_CONFIGS = ("pytest.ini", "conftest.py")
_JS_DIRS = ("tests", "test", "__tests__", "spec", "e2e")
_PY_DIRS = ("tests", "test")


def _stack_test_paths(project: Path, commands: list[str]) -> tuple[list[str], list[str]]:
    """Return (dirs, configs) narrowed to the project's actual stack."""
    # resolve `npm test` / `npm run X` through package.json
    resolved = list(commands)
    pkg_path = project / "package.json"
    if pkg_path.is_file():
        try:
            import json
            scripts = json.loads(pkg_path.read_text(encoding="utf-8")).get("scripts", {})
            for cmd in commands:
                parts = cmd.strip().split()
                if len(parts) >= 2 and parts[0] == "npm":
                    key = parts[1] if parts[1] != "run" else (parts[2] if len(parts) > 2 else "")
                    if key in scripts:
                        resolved.append(scripts[key])
        except Exception:  # noqa: BLE001
            pass
    joined = " ".join(resolved).lower()
    has_js = pkg_path.is_file()
    has_py = any((project / m).is_file() for m in ("pyproject.toml", "setup.py", "setup.cfg"))
    # detect framework from commands
    frameworks = [fw for fw in _JS_CONFIGS if fw in joined]
    if frameworks:
        dirs = list(dict.fromkeys(d for d in _JS_DIRS))
        cfgs = [c for fw in frameworks for c in _JS_CONFIGS[fw]]
        return dirs, cfgs
    if "pytest" in joined or "python" in joined:
        return list(_PY_DIRS), list(_PY_CONFIGS)
    # fallback to project markers
    if has_js and not has_py:
        dirs = list(_JS_DIRS)
        cfgs = [c for fw_cfgs in _JS_CONFIGS.values() for c in fw_cfgs]
        return dirs, cfgs
    if has_py and not has_js:
        return list(_PY_DIRS), list(_PY_CONFIGS)
    # both or neither: add everything
    dirs = list(dict.fromkeys(list(_JS_DIRS) + list(_PY_DIRS)))
    cfgs = [c for fw_cfgs in _JS_CONFIGS.values() for c in fw_cfgs] + list(_PY_CONFIGS)
    return dirs, cfgs


def verification_paths(story: Story, project: Path, config=None) -> list[str]:
    """Test directories/files the **story's verification contract** requires.

    Bug 21 (e9 2026-09-05): story declared `e2e` and `accessibility` but
    write_scope only had `src/**`; guard blocked writing `tests/`, $30 wasted.
    If the harness requires tests, it must grant scope to write them.

    Bug 22 (e9 2026-09-08, greenfield): verification_paths only added paths
    that **exist**, but in a greenfield project the test directory doesn't
    exist yet — the story must CREATE it. Now also adds conventional test
    dirs and config files when the verification contract requires test kinds.
    """
    kinds = [k.strip().lower() for k in (story.verification_contract or []) if k.strip()]
    if not kinds:
        return []
    if config is None:
        from ..config import Config

        try:
            config = Config.load(project)
        except Exception:  # noqa: BLE001 — no config means nothing to infer
            return []
    out: list[str] = []
    needs_tests = any(k in kinds for k in ("unit", "e2e", "accessibility", "integration"))

    for kind in kinds:
        key = _VERIFY_COMMAND_KEY.get(kind, f"verify.{kind}")
        try:
            cmd = str(config[key] or "")
        except KeyError:
            continue
        for tok in cmd.replace("'", " ").replace('"', " ").split():
            if tok.startswith("-") or "/" not in tok:
                continue
            rel = tok.strip("./").rstrip("/")
            if not rel or rel.startswith("..") or rel.startswith("node_modules"):
                continue
            if rel not in out:
                out.append(rel)

    if needs_tests and not out:
        commands = []
        for kind in kinds:
            key = _VERIFY_COMMAND_KEY.get(kind, f"verify.{kind}")
            try:
                cmd = str(config[key] or "")
            except KeyError:
                continue
            if cmd:
                commands.append(cmd)
        dirs, cfgs = _stack_test_paths(project, commands)
        for d in dirs:
            if d not in out:
                out.append(d)
        for cfg in cfgs:
            if cfg not in out:
                out.append(cfg)

    return out


def is_lockfile(path: str) -> bool:
    """Is this path a lockfile added by `with_lockfiles`?

    The "story touches too many places" threshold measures **how large the
    story declares itself**. Lockfiles are an automatic consequence of the
    manifest, so counting them toward the threshold would turn a correct
    patch into a gate failure.
    """
    name = path.rstrip("/").rsplit("/", 1)[-1]
    return any(name in locks for locks in LOCKFILES.values())


def with_lockfiles(scope: list[str]) -> list[str]:
    """Add lockfiles of every manifest in scope.

    Adds the **entire family** of lockfiles for each manifest rather than
    guessing the package manager in use: an extra path in scope does not
    meaningfully loosen it — a non-existent file cannot be written — but
    guessing wrong puts the story right back into the same deadlock.
    """
    have = set(scope)
    out = list(scope)
    for path in scope:
        name = path.rstrip("/").rsplit("/", 1)[-1]
        prefix = path[: len(path) - len(name)]
        for lock in LOCKFILES.get(name, ()):
            if prefix + lock not in have:
                have.add(prefix + lock)
                out.append(prefix + lock)
    return out


@dataclass
class PRD:
    requirements: list[Requirement] = field(default_factory=list)
    assumptions: list[str] = field(default_factory=list)
    open_questions: list[OpenQuestion] = field(default_factory=list)

    def functional(self) -> list[Requirement]:
        return [r for r in self.requirements if r.kind == "functional"]

    def non_functional(self) -> list[Requirement]:
        return [r for r in self.requirements if r.kind == "non_functional"]

    def by_id(self, req_id: str) -> Requirement | None:
        return next((r for r in self.requirements if r.id == req_id), None)

    def blocked_ids(self) -> set[str]:
        """Requirements blocked by open questions — must not be included in stories."""
        blocked: set[str] = set()
        for oq in self.open_questions:
            blocked |= set(oq.blocks)
        return blocked

    def untestable(self) -> list[Requirement]:
        return [r for r in self.functional() if not r.is_testable]

    def as_dict(self) -> dict:
        return {
            "requirements": [
                {
                    "id": r.id,
                    "kind": r.kind,
                    "title": r.title,
                    "description": r.description,
                    "acceptance_criteria": r.acceptance_criteria,
                    "open_questions": r.open_questions,
                }
                for r in self.requirements
            ],
            "assumptions": self.assumptions,
            "open_questions": [
                {"id": q.id, "text": q.text, "blocks": q.blocks}
                for q in self.open_questions
            ],
        }


def _expand_fr_refs(text: str) -> list[str]:
    """`FR-13..FR-15` -> [FR-13, FR-14, FR-15]; includes single references too."""
    ids: list[str] = []
    consumed = text
    for m in _FR_RANGE.finditer(text):
        start, end = int(m.group(1)), int(m.group(2))
        if start <= end and end - start < 100:
            ids.extend(f"FR-{n}" for n in range(start, end + 1))
            consumed = consumed.replace(m.group(0), " ")
        # Reversed or overly wide range is a writing error. Not expanded, but
        # also not removed from text — the two codes at each end are still
        # picked up as single references. Blocking one extra is safer than
        # missing both.
    ids.extend(f"FR-{m.group(1)}" for m in _FR_SINGLE.finditer(consumed))
    return sorted(set(ids), key=lambda s: int(s.split("-")[1]))


def _section_for(text: str, start: int, next_start: int | None) -> str:
    return text[start : next_start if next_start is not None else len(text)]


def parse_prd(text: str) -> PRD:
    """Parse a BMAD PRD into the framework's data model."""
    prd = PRD()

    fr_matches = list(_FR_HEADING.finditer(text))
    for i, m in enumerate(fr_matches):
        body = _section_for(
            text, m.end(), fr_matches[i + 1].start() if i + 1 < len(fr_matches) else None
        )

        criteria: list[str] = []
        cons = _CONSEQUENCES.search(body)
        if cons:
            criteria = [b.group(1).strip() for b in _BULLET.finditer(cons.group(1))]

        # Fallback: last bold-text heading or markdown heading followed by a
        # bullet/numbered list in the FR body.
        if not criteria:
            _last_block = None
            for _fb in re.finditer(
                r"(?:^\*\*[^*\n]+\*\*|^#{3,5}\s+\S[^\n]*)[:：]?\s*$\s*\n",
                body, re.MULTILINE,
            ):
                _rest = body[_fb.end():]
                _end = re.search(r"\n#{2,5}\s|\n\*\*|\Z", _rest, re.MULTILINE)
                _blk = _rest[: _end.start()] if _end else _rest
                _items = [b.group(1).strip() for b in _BULLET.finditer(_blk)]
                if _items:
                    _last_block = (_fb, _items)
            if _last_block:
                cons, criteria = _last_block[0], _last_block[1]

        description = body[: cons.start()] if cons else body
        description = _ASSUMPTION.sub("", description)

        prd.requirements.append(
            Requirement(
                id=m.group(1),
                kind="functional",
                title=m.group(2).strip(),
                description=" ".join(description.split())[:600],
                acceptance_criteria=criteria,
                open_questions=sorted(set(_OQ_MENTION.findall(body))),
            )
        )

    nfr_matches = list(_NFR_ITEM.finditer(text))
    for i, m in enumerate(nfr_matches):
        nfr_id = m.group(1) or m.group(4)
        nfr_title = m.group(2) or m.group(5) or ""
        nfr_desc = m.group(3) or ""
        if m.group(4) and not nfr_desc:
            body_start = m.end()
            body_end = nfr_matches[i + 1].start() if i + 1 < len(nfr_matches) else None
            nfr_desc = _section_for(text, body_start, body_end)
        prd.requirements.append(
            Requirement(
                id=nfr_id,
                kind="non_functional",
                title=nfr_title.strip(),
                description=" ".join(_ASSUMPTION.sub("", nfr_desc).split())[:600],
                open_questions=sorted(set(_OQ_MENTION.findall(
                    text[m.start():nfr_matches[i + 1].start()] if i + 1 < len(nfr_matches)
                    else text[m.start():]
                ))),
            )
        )

    # Fallback: agent wrote NFR section but omitted NFR-N IDs — auto-number.
    if not prd.non_functional():
        sec = _NFR_SECTION.search(text)
        if sec:
            after = text[sec.end():]
            end = re.search(r"\n#{2,5}\s", after)
            block = after[: end.start()] if end else after
            for i, bm in enumerate(_PLAIN_BULLET.finditer(block), start=1):
                line = bm.group(1).strip()
                if not line or line.startswith("#"):
                    break
                parts = re.split(r"[—–-]\s+", line, maxsplit=1)
                title = parts[0].strip().strip("*").strip()
                desc = parts[1].strip() if len(parts) > 1 else ""
                prd.requirements.append(
                    Requirement(
                        id=f"NFR-{i}",
                        kind="non_functional",
                        title=title,
                        description=desc[:600],
                    )
                )

    seen_assumptions: set[str] = set()
    for m in _ASSUMPTION.finditer(text):
        a = " ".join(m.group(1).split())
        if a not in seen_assumptions:
            seen_assumptions.add(a)
            prd.assumptions.append(a)

    # Fallback: assumptions in a dedicated section (no inline markers).
    if not prd.assumptions:
        asec = _ASSUMPTION_SECTION.search(text)
        if asec:
            after = text[asec.end():]
            end = re.search(r"\n#{2,5}\s", after)
            block = after[: end.start()] if end else after
            for bm in _SECTION_ASSUMPTION_ITEM.finditer(block):
                a = " ".join(bm.group(1).split())
                if a and a not in seen_assumptions:
                    seen_assumptions.add(a)
                    prd.assumptions.append(a)

    seen_oq: set[str] = set()
    for m in _OQ_DEFINITION.finditer(text):
        oq_id = m.group(1) or m.group(4)
        if oq_id in seen_oq:
            continue
        seen_oq.add(oq_id)
        prd.open_questions.append(
            OpenQuestion(
                id=oq_id,
                text=" ".join((m.group(3) or m.group(6)).split())[:400],
                blocks=_expand_fr_refs(m.group(2) or m.group(5) or ""),
            )
        )

    return prd


def parse_prd_file(path: Path | str) -> PRD:
    return parse_prd(Path(path).read_text(encoding="utf-8", errors="replace"))


# ----------------------------------------------------------------- epics.md

#: `## Epic 1: Note-taking foundation`
_EPIC_HEADING = re.compile(r"^#{2,5}\s+Epic\s+(\d+)\s*[:：—–-]\s*(.+?)\s*$", re.MULTILINE | re.IGNORECASE)
#: `### Story 1.2: Edit note` — fixed pattern in BMAD template.
_STORY_HEADING = re.compile(
    r"^#{2,5}\s+Story\s+(\d+)\.(\d+)\s*[:：—–-]\s*(.+?)\s*$", re.MULTILINE | re.IGNORECASE
)
#: Acceptance criteria block ends at a new heading or another **bold label**
#: — but *not* at `**When**`/`**Then**`/`**And**`, which are body parts of
#: the criteria themselves. Cutting there leaves each story with one truncated criterion.
_AC_HEAD = (
    r"(?:Acceptance Criteria|Tiêu chí chấp nhận|Tiêu chí kiểm chứng"
    r"|Tiêu chí nghiệm thu"
    r"|(?:Testable|Verifiable|Acceptance|Verification|Test)\s+(?:criteria|consequences|conditions)"
    r"|Criteria|Tiêu chí|Hệ quả(?:\s+kiểm chứng(?:\s+được)?)?)"
)
_AC_BLOCK = re.compile(
    r"(?:\*\*" + _AC_HEAD + r"\s*[:：]?\*\*"
    r"|#{2,5}\s+" + _AC_HEAD + r")"
    r"\s*[:：]?\s*\n(.*?)"
    r"(?=\n#{2,5}\s|\n\s*\*\*(?!Given|When|Then|And)[^\n*]+\*\*\s*[:：]?\s*\n|\Z)",
    re.DOTALL | re.IGNORECASE,
)
_GIVEN = re.compile(r"^\s*\*\*Given\*\*", re.IGNORECASE)
#: `- write_scope: src/notes/, src/db/schema.ts` — including when labels are bold.
_META_ITEM = re.compile(
    r"^[-*]?\s*\*{0,2}(covers|write[_ ]scope|depends[_ ]on|screens?|verification[_ ]contract)\*{0,2}\s*[:：]\s*(.+?)\s*$",
    re.MULTILINE | re.IGNORECASE,
)
_STORY_REF = re.compile(r"\b(\d+)\.(\d+)\b")
#: Coverage map lines that explicitly say there is **no** story. Skip them:
#: a real BMAD line is "FR-13 -> NO STORY. ... Binds AR-18 at Story 1.2",
#: and if we only look for "has FR code + has story number" then FR-13 gets
#: assigned to story 1.2 — then the machine gate blocks the entire story set
#: because of one prose sentence.
_NO_STORY = re.compile(
    r"(không có story|chưa có story|no story|ngoài phạm vi|out of scope|n/a)", re.I
)
_ROLE_LINE = re.compile(
    r"^\s*(?:As an?|Tôi là)\s+(.+?),?\s*$\n"
    r"^\s*(?:I want|Tôi muốn)\s+(.+?),?\s*$\n"
    r"^\s*(?:So that|Để)\s+(.+?)\.?\s*$",
    re.MULTILINE | re.IGNORECASE,
)


def epic_id(n: int | str) -> str:
    return f"EPIC-{int(n):02d}"


def story_id(epic: int | str, seq: int | str) -> str:
    return f"STORY-{int(epic):02d}-{int(seq):02d}"


@dataclass
class Story:
    """A normalized story — the unit of work for one agent session."""

    id: str
    epic_id: str
    title: str
    as_a: str = ""
    i_want: str = ""
    so_that: str = ""
    acceptance_criteria: list[str] = field(default_factory=list)
    #: FR codes this story covers. Machine gate cross-references with the PRD.
    covers: list[str] = field(default_factory=list)
    #: Paths the story is allowed to write. Guard blocks according to this list,
    #: and merge conflicts at wave end are evidence of a misdeclared scope.
    write_scope: list[str] = field(default_factory=list)
    depends_on: list[str] = field(default_factory=list)
    #: Screens this story builds (codes from EXPERIENCE.md). Empty = story has
    #: no UI; the mockup map step skips it.
    screens: list[str] = field(default_factory=list)
    #: Verification kinds this story must pass. If the story declares them,
    #: the declaration is used; otherwise inferred by code. Not a new phase —
    #: just making explicit what "done" means for **this story**, instead of
    #: a single default for all stories.
    verification_contract: list[str] = field(default_factory=list)
    body: str = ""

    @property
    def epic_seq(self) -> tuple[int, int]:
        parts = self.id.split("-")
        return int(parts[1]), int(parts[2])

    def as_dict(self) -> dict:
        return {
            "id": self.id,
            "epic_id": self.epic_id,
            "title": self.title,
            "as_a": self.as_a,
            "i_want": self.i_want,
            "so_that": self.so_that,
            "acceptance_criteria": self.acceptance_criteria,
            "covers": self.covers,
            "write_scope": self.write_scope,
            "verification_contract": self.verification_contract,
            "depends_on": self.depends_on,
            "screens": self.screens,
        }


@dataclass
class Epic:
    id: str
    title: str
    goal: str = ""
    stories: list[Story] = field(default_factory=list)


@dataclass
class EpicPlan:
    epics: list[Epic] = field(default_factory=list)
    #: FR -> story, read from the "FR Coverage Map" section if BMAD generated one.
    coverage_map: dict[str, list[str]] = field(default_factory=dict)

    def stories(self) -> list[Story]:
        return [s for e in self.epics for s in e.stories]

    def by_id(self, sid: str) -> Story | None:
        return next((s for s in self.stories() if s.id == sid), None)


def _split_ac(block: str) -> list[str]:
    """Split an acceptance criteria block into individual criteria.

    Two patterns observed in practice: multi-line Given/When/Then, and
    bullet lists. Given opens a new criterion; otherwise each bullet is
    one criterion.
    """
    items: list[str] = []
    current: list[str] = []

    for raw in block.splitlines():
        line = raw.strip()
        if not line or _META_ITEM.match(line):
            continue  # metadata line, not a criterion
        if _GIVEN.match(line):
            if current:
                items.append(" ".join(current))
            current = [line]
        elif current:
            current.append(line)
        else:
            m = _BULLET.match(line)
            items.append(m.group(1) if m else line)
    if current:
        items.append(" ".join(current))

    cleaned = [" ".join(i.replace("**", "").split()) for i in items]
    return [c for c in cleaned if c]


def _split_list(text: str) -> list[str]:
    """`a, b · c` -> ['a', 'b', 'c']. Strips quotes and bold markers."""
    parts = re.split(r"[,;·]| và ", text)
    return [p.strip().strip("`\"'*") for p in parts if p.strip().strip("`\"'*")]


def _parse_story_meta(body: str, epic_n: int) -> dict[str, list[str]]:
    meta: dict[str, list[str]] = {}
    for m in _META_ITEM.finditer(body):
        key = m.group(1).lower().replace(" ", "_")
        values = _split_list(m.group(2))
        if key == "covers":
            meta["covers"] = _expand_fr_refs(m.group(2))
        elif key == "verification_contract":
            meta["verification_contract"] = [v.strip().lower() for v in values if v.strip()]
        elif key == "write_scope":
            meta["write_scope"] = [v for v in values if v.lower() not in ("none", "không")]
        elif key == "depends_on":
            meta["depends_on"] = _refs_to_story_ids(m.group(2), epic_n)
        elif key in ("screen", "screens"):
            meta["screens"] = [
                slugify(v) for v in values if v.lower() not in ("none", "không")
            ]
    return meta


def _refs_to_story_ids(text: str, default_epic: int) -> list[str]:
    """`1.1, 2.3` or `STORY-01-01` -> normalized story id."""
    out = []
    for m in re.finditer(r"STORY-(\d+)-(\d+)", text, re.IGNORECASE):
        out.append(story_id(m.group(1), m.group(2)))
    for m in _STORY_REF.finditer(text):
        sid = story_id(m.group(1), m.group(2))
        if sid not in out:
            out.append(sid)
    return out


def _parse_coverage_map(text: str) -> dict[str, list[str]]:
    """Parse the "FR Coverage Map" section — table or bullet list, both accepted.

    Any line with at least one FR code and one story number counts as a
    mapping line; no rigid table format, because the model formats
    differently each time.
    """
    m = re.search(r"^#{2,4}\s+(?:FR[- ]?(?:Story\s+)?Coverage\s+Map|(?:Requirements?\s+)?Coverage(?:\s+Map)?|Bản đồ phủ FR)\s*$", text, re.MULTILINE | re.IGNORECASE)
    if not m:
        return {}
    section = text[m.end():]
    end = re.search(r"^#{2,3}\s+\S", section, re.MULTILINE)
    if end:
        section = section[: end.start()]

    mapping: dict[str, list[str]] = {}
    for line in section.splitlines():
        frs = _expand_fr_refs(line)
        if not frs or _NO_STORY.search(line):
            continue
        refs = [story_id(a, b) for a, b in _STORY_REF.findall(line)]
        for fr in frs:
            mapping.setdefault(fr, [])
            for r in refs:
                if r not in mapping[fr]:
                    mapping[fr].append(r)
    return mapping


def parse_epics(text: str) -> EpicPlan:
    """BMAD's `epics.md` -> normalized epics and stories."""
    plan = EpicPlan(coverage_map=_parse_coverage_map(text))

    epic_marks = list(_EPIC_HEADING.finditer(text))
    for i, em in enumerate(epic_marks):
        epic_n = int(em.group(1))
        end = epic_marks[i + 1].start() if i + 1 < len(epic_marks) else len(text)
        section = text[em.end():end]
        epic = Epic(id=epic_id(epic_n), title=em.group(2).strip())

        story_marks = list(_STORY_HEADING.finditer(section))
        epic.goal = " ".join(
            section[: story_marks[0].start() if story_marks else len(section)].split()
        )[:600]

        for j, sm in enumerate(story_marks):
            s_end = story_marks[j + 1].start() if j + 1 < len(story_marks) else len(section)
            body = section[sm.end():s_end]
            story = Story(
                id=story_id(epic_n, sm.group(2)),
                epic_id=epic.id,
                title=sm.group(3).strip(),
                body=body.strip(),
            )

            role = _ROLE_LINE.search(body)
            if role:
                story.as_a, story.i_want, story.so_that = (
                    " ".join(g.split()) for g in role.groups()
                )

            ac = _AC_BLOCK.search(body)
            if ac:
                story.acceptance_criteria = _split_ac(ac.group(1))

            meta = _parse_story_meta(body, epic_n)
            story.covers = meta.get("covers", [])
            story.write_scope = with_lockfiles(meta.get("write_scope", []))
            story.depends_on = [d for d in meta.get("depends_on", []) if d != story.id]
            story.screens = meta.get("screens", [])
            story.verification_contract = meta.get("verification_contract", [])

            epic.stories.append(story)
        plan.epics.append(epic)

    # Coverage map is the fallback source: if a story doesn't declare `covers`
    # it comes from here, because missing FR mappings make the machine gate
    # block the entire story set.
    for fr, sids in plan.coverage_map.items():
        for sid in sids:
            st = plan.by_id(sid)
            if st and fr not in st.covers:
                st.covers.append(fr)

    return plan


def parse_epics_file(path: Path | str) -> EpicPlan:
    return parse_epics(Path(path).read_text(encoding="utf-8", errors="replace"))


# ---------------------------------------------------------- architecture.md

#: `### AR-1 — Single write path`
_AR_HEADING = re.compile(r"^#{2,4}\s+((?:AR|AD)-\d+)\s*[—–:-]\s*(.+?)\s*$", re.MULTILINE | re.IGNORECASE)
_AR_FIELD = re.compile(r"^[-*]\s*\*\*(Binds|Prevents|Rule)\s*[:：]?\*\*\s*(.+)$", re.MULTILINE)


@dataclass
class Decision:
    """An architectural decision that stories must comply with."""

    id: str
    title: str
    #: Requirement codes this decision binds — this is how to select the right
    #: decisions for a story without guessing.
    binds: list[str] = field(default_factory=list)
    #: Decision applies to **all** stories (`Binds: all`, or no bindings
    #: declared). This is a baseline rule, not a requirement-specific one.
    universal: bool = False
    prevents: str = ""
    rule: str = ""
    text: str = ""

    def as_prompt(self) -> str:
        parts = [f"**{self.id} — {self.title}**"]
        if self.rule:
            parts.append(f"Rule: {self.rule}")
        if self.prevents:
            parts.append(f"Prevents: {self.prevents}")
        return "\n".join(parts)


@dataclass
class Architecture:
    decisions: list[Decision] = field(default_factory=list)

    def by_id(self, ar_id: str) -> Decision | None:
        return next((d for d in self.decisions if d.id == ar_id), None)

    def for_requirements(self, fr_ids: list[str]) -> list[Decision]:
        """Decisions binding any requirement in the list.

        Thanks to the ``**Binds:**`` field, selecting context for a story is
        a **lookup**, not a judgment call: loading the entire 26KB architecture
        document into every session is both expensive and diluting, and
        letting the agent self-select means every session selects differently.
        """
        want = set(fr_ids)
        return [d for d in self.decisions if d.universal or (want & set(d.binds))]


def parse_architecture(text: str) -> Architecture:
    arch = Architecture()
    marks = list(_AR_HEADING.finditer(text))
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(text)
        body = text[m.end():end]
        d = Decision(id=m.group(1), title=m.group(2).strip(), text=body.strip())
        seen_binds = False
        for f in _AR_FIELD.finditer(body):
            seen_binds = seen_binds or f.group(1).lower() == "binds"
            key, value = f.group(1).lower(), " ".join(f.group(2).split())
            if key == "binds":
                d.binds = _expand_fr_refs(value) + re.findall(r"\b(?:AR|AD)-\d+\b", value)
                d.universal = bool(re.search(r"\b(all|mọi story|toàn bộ)\b", value, re.I))
            elif key == "prevents":
                d.prevents = value
            else:
                d.rule = value
        # No bindings declared = baseline rule, applies to all stories. Treating
        # it as "applies to no story" would drop exactly the most important rules.
        d.universal = d.universal or not seen_binds
        arch.decisions.append(d)
    return arch


def parse_architecture_file(path: Path | str) -> Architecture:
    return parse_architecture(Path(path).read_text(encoding="utf-8", errors="replace"))
