"""Isolate parallel stories using git worktrees.

Wave partitioning by ``write_scope`` only prevents *file content* collisions.
Three things still clash when multiple stories share a working directory:

* concurrent ``git add`` / ``git commit`` fighting over ``index.lock``;
* concurrent tests fighting over network ports, databases, temp files;
* concurrent dependency installs corrupting ``node_modules`` / venv.

Each story in a wave therefore runs in its own worktree with its own branch.
Worktrees share ``.git`` so creation is fast and disk-cheap.

After a wave, branches are **merged sequentially** into the main branch. See
``merge_story`` for why a conflict here is a signal, not an incident.
Mechanism validated in spike S5 (`docs/SPIKE-REPORT.md`).
"""

from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
import threading
import time
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path

from aisef._compat import flock_ex_nb, flock_un

#: Worktree directory, relative to the repo root.
WORKTREE_ROOT = ".aisef/worktrees"

#: Story branch name prefix.
BRANCH_PREFIX = "story/"

_SAFE = re.compile(r"[^A-Za-z0-9._-]+")


class GitError(RuntimeError):
    """A git command failed."""


def _git(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    proc = subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True,
        text=True,
        timeout=30,
    )
    if check and proc.returncode != 0:
        raise GitError(f"git {' '.join(args)}: {proc.stderr.strip() or proc.stdout.strip()}")
    return proc


def commit_paths(path: Path, message: str, *, paths: list[str] | None = None) -> bool:
    """Commit remaining uncommitted work in a working tree. False means nothing to commit.

    Stage **only the declared write scope**, not `add -A` (invariant 5).
    `diff-scope` usually already confirmed the tree is within scope, so both
    approaches give the same result — but only when the guard has run. Staging
    by scope is correct even when it hasn't, and that is what the invariant protects.
    """
    if not _git(path, "status", "--porcelain", check=False).stdout.strip():
        return False  # agent already committed everything

    # Only stage paths that **actually exist**: a story declaring a file then
    # not creating it is common, especially on mid-run failures, and `git add`
    # with a non-matching pathspec breaks the whole command. Dropping missing
    # paths doesn't loosen anything — still not `add -A`.
    co_that = [p for p in (paths or []) if (path / p).exists()]
    if co_that:
        _git(path, "add", "--", *co_that)
    else:
        _git(path, "add", "-u")  # no scope declared: only tracked files
    if not _git(path, "diff", "--cached", "--name-only", check=False).stdout.strip():
        return False
    _git(path, "commit", "-q", "-m", message)
    return True


def main_repo(path: Path | str) -> Path:
    """Main repository root for a given path, even when inside a worktree.

    Stories run in separate worktrees, but evidence and state must be written
    to **a single artifact root** (invariant 2). Otherwise each story writes
    to its own root and the gate reading from the main root sees nothing.
    """
    path = Path(path).resolve()
    proc = subprocess.run(
        ["git", "-C", str(path), "rev-parse", "--path-format=absolute", "--git-common-dir"],
        capture_output=True, text=True, timeout=10,
    )
    if proc.returncode != 0 or not proc.stdout.strip():
        return path
    common = Path(proc.stdout.strip())
    return common.parent if common.name == ".git" else path


def safe_slug(story_id: str) -> str:
    """Convert a story id into a safe branch/directory name slug."""
    slug = _SAFE.sub("-", story_id).strip("-")
    if not slug:
        raise ValueError(f"unusable story id: {story_id!r}")
    return slug


@dataclass(frozen=True)
class Worktree:
    story_id: str
    path: Path
    branch: str
    #: Main branch merged in on reconnect, or "" if not needed.
    #: Recorded so readers know which base this worktree stands on.
    refreshed_from: str = ""


@dataclass
class MergeResult:
    story_id: str
    branch: str
    merged: bool
    conflicts: list[str] = field(default_factory=list)
    message: str = ""

    @property
    def scope_was_misdeclared(self) -> bool:
        """A conflict means two stories touched the same region.

        The scheduler only places stories with disjoint ``write_scope`` in
        the same wave, so a merge conflict means the scope was misdeclared.
        """
        return bool(self.conflicts)


#: Client config generated by `compile` that the project may not commit.
CLIENT_CONFIG = (".claude/settings.json", ".opencode")


class WorktreeManager:
    """Create, clean up, and merge story worktrees."""

    # git worktree add races on .git/worktrees metadata under ThreadPoolExecutor
    _create_lock = threading.Lock()

    def __init__(self, repo: Path, *, root: str = WORKTREE_ROOT):
        self.repo = Path(repo).resolve()
        self.root = self.repo / root
        if not (self.repo / ".git").exists():
            raise GitError(f"{self.repo} is not a git repository")

    # ------------------------------------------------------------ create, clean up

    def path_for(self, story_id: str) -> Path:
        return self.root / safe_slug(story_id)

    def branch_for(self, story_id: str) -> str:
        return f"{BRANCH_PREFIX}{safe_slug(story_id)}"

    def has_branch(self, story_id: str) -> bool:
        """Whether the story branch still exists — after the worktree is removed,
        the branch holds the work and is a candidate for re-verification."""
        return self._branch_exists(self.branch_for(story_id))

    def create(self, story_id: str, *, base: str | None = None,
               refresh: bool = True) -> Worktree:
        """Create a worktree for a story. Idempotent: returns existing one if present.

        If the branch already exists, **merge the main branch in before handing
        off to the agent** — unless ``refresh=False``: re-verification (ADR-004
        R13) grades the exact candidate frozen at the story branch HEAD, and a
        merge commit creates a new revision that makes all prior evidence stale.
        Without this, a retried story still stands on the trunk at the point it
        forked: config fixes, tool patches, and work from stories merged in
        earlier waves never arrive. Measured on project `par`:
        `story/STORY-01-01` forked from `e0a6b4e`, the test command patch was
        at `963dae3`, and the story failed due to exactly the bug fixed on main.

        Merge, not rebase: rebase rewrites the agent's commit history, and a
        conflict mid-way through a commit chain is unresolvable.
        """
        path, branch = self.path_for(story_id), self.branch_for(story_id)
        if (path / ".git").exists():
            return Worktree(story_id, path, branch)
        with self._create_lock:
            if (path / ".git").exists():
                return Worktree(story_id, path, branch)
            if path.exists():
                shutil.rmtree(path)
                _git(self.repo, "worktree", "prune")

            self._ensure_root()
            co_san = self._branch_exists(branch)
            args = ["worktree", "add", "-q"]
            if co_san:
                args += [str(path), branch]
            else:
                args += [str(path), "-b", branch]
                if base:
                    args.append(base)
            _git(self.repo, *args)
        self._carry_client_config(path)

        mang_vao = self.refresh(story_id, base=base) if co_san and refresh else ""
        return Worktree(story_id, path, branch, refreshed_from=mang_vao)

    def _carry_client_config(self, path: Path) -> list[str]:
        """Copy client config generated by `compile` into the worktree when it
        hasn't been committed. Claude receives `--settings` explicitly, but
        OpenCode only reads `.opencode/` from its working directory — without
        copying, guards don't reach it. Measured in conformance 2026-09-05:
        OpenCode C1 `rm -rf` ran for real, file lost, because the worktree
        had no plugin."""
        chep = []
        for rel in CLIENT_CONFIG:
            src, dst = self.repo / rel, path / rel
            if not src.exists() or dst.exists():
                continue
            dst.parent.mkdir(parents=True, exist_ok=True)
            if src.is_dir():
                shutil.copytree(src, dst)
            else:
                shutil.copy2(src, dst)
            chep.append(rel)
        return chep

    def refresh(self, story_id: str, *, base: str | None = None) -> str:
        """Merge the main branch into the story branch. Returns source branch name, or "".

        On conflict, aborts and **raises an error**: a story running on a stale
        trunk works on the wrong base, and hiding that only surfaces the error
        at the end-of-wave merge, far from where it was caused.
        """
        path = self.path_for(story_id)
        goc = base or self._current_branch()
        if not goc or not path.is_dir():
            return ""
        # Already contains the main branch tip — no merge needed; avoids
        # creating an empty merge commit on every rerun.
        dau = _git(self.repo, "rev-parse", goc, check=False).stdout.strip()
        if dau and _git(
            path, "merge-base", "--is-ancestor", dau, "HEAD", check=False
        ).returncode == 0:
            return ""

        proc = _git(path, "merge", "--no-edit", goc, check=False)
        if proc.returncode == 0:
            return goc
        dung = [
            l.strip()
            for l in _git(path, "diff", "--name-only", "--diff-filter=U",
                          check=False).stdout.splitlines()
            if l.strip()
        ]
        _git(path, "merge", "--abort", check=False)
        raise GitError(
            f"{story_id}: cannot merge `{goc}` into story branch — conflicts in "
            f"{', '.join(dung[:5]) or 'unknown files'}. Story branch has diverged too "
            f"far; delete the branch and rerun, or merge manually."
        )

    def _current_branch(self) -> str:
        out = _git(self.repo, "rev-parse", "--abbrev-ref", "HEAD", check=False).stdout.strip()
        return "" if out in ("", "HEAD") else out

    def remove(self, story_id: str, *, delete_branch: bool = False) -> None:
        """Remove the worktree. Does not delete the branch unless requested —
        committed work must not disappear just because the directory is cleaned up."""
        path = self.path_for(story_id)
        if path.exists():
            _git(self.repo, "worktree", "remove", "--force", str(path), check=False)
            if path.exists():
                shutil.rmtree(path, ignore_errors=True)
        _git(self.repo, "worktree", "prune", check=False)
        if delete_branch:
            _git(self.repo, "branch", "-D", self.branch_for(story_id), check=False)

    def list_active(self) -> list[str]:
        """Story ids that currently have a worktree."""
        if not self.root.is_dir():
            return []
        return sorted(p.name for p in self.root.iterdir() if p.is_dir())

    @contextmanager
    def temporary(self, sha: str, *, label: str = "qa") -> Iterator[Path]:
        """Temporary **detached** worktree at exactly ``sha``; removed on exit
        from the ``with`` block, even if an exception is raised inside.

        For project-level verification (ADR-005 V6): the tree under test is
        reconstructed from SHA, not the working tree the agent (or human) just
        edited — uncommitted shims like `node_modules/.bin/*`, `pytest.ini`,
        `conftest.py` cannot reach here. No branch is created: nothing to keep
        after verification. Directory is created via ``mkdtemp`` so two calls
        with the same SHA don't collide.
        """
        self._ensure_root()
        path = Path(tempfile.mkdtemp(prefix=f"{label}-{sha[:7]}-", dir=self.root))
        try:
            _git(self.repo, "worktree", "add", "-q", "--detach", str(path), sha)
        except GitError:
            shutil.rmtree(path, ignore_errors=True)
            raise
        try:
            yield path
        finally:
            _git(self.repo, "worktree", "remove", "--force", str(path), check=False)
            if path.exists():
                shutil.rmtree(path, ignore_errors=True)
            _git(self.repo, "worktree", "prune", check=False)

    # ------------------------------------------------------------ merging

    def commit_story(
        self, story_id: str, message: str = "", *, paths: list[str] | None = None
    ) -> bool:
        """Commit remaining uncommitted work in a story's worktree.

        Agents are encouraged to commit incrementally, but the harness commits
        whatever is left: merge only sees committed content, so skipping this
        step leaves the story "done" with work that never reaches the main branch.

        Stage **only the story's declared write scope**, not `add -A` (invariant 5).
        `diff-scope` just confirmed the tree is within scope, so both approaches
        give the same result — but only when the guard has run. Staging by scope
        is correct even when it hasn't, and that is what the invariant protects.
        """
        path = self.path_for(story_id)
        if not path.is_dir():
            return False
        return commit_paths(path, message or f"{story_id}: done", paths=paths)

    MERGE_LOCK_TIMEOUT = 120

    @contextmanager
    def _merge_lock(self) -> Iterator[None]:
        """Merge lock — only one machine merges into the main branch at a time."""
        lock_path = self.repo / ".aisef" / "merge.lock"
        lock_path.parent.mkdir(parents=True, exist_ok=True)
        fh = open(lock_path, "w")
        deadline = time.monotonic() + self.MERGE_LOCK_TIMEOUT
        while True:
            try:
                flock_ex_nb(fh.fileno())
                break
            except OSError:
                if time.monotonic() >= deadline:
                    fh.close()
                    raise GitError("merge lock timeout — another machine is merging")
                time.sleep(0.1)
        try:
            yield
        finally:
            flock_un(fh.fileno())
            fh.close()

    def merge_story(self, story_id: str, *, into: str | None = None) -> MergeResult:
        """Merge a story branch into the main branch.

        On conflict, **aborts immediately** and returns the list of conflicting
        files. Does not auto-resolve: per the scheduler, two stories in the same
        wave should never touch the same region, so a conflict is evidence that
        ``write_scope`` was misdeclared — needs a human to review the story
        split, not a cleverer merge.

        Merge lock ensures only one machine merges at a time (distributed).
        """
        with self._merge_lock():
            return self._merge_story_inner(story_id, into=into)

    def _merge_story_inner(self, story_id: str, *, into: str | None = None) -> MergeResult:
        branch = self.branch_for(story_id)
        if into:
            _git(self.repo, "checkout", "-q", into)

        proc = _git(self.repo, "merge", "--no-edit", branch, check=False)
        if proc.returncode == 0:
            return MergeResult(story_id, branch, True, message=proc.stdout.strip())

        conflicts = [
            l.strip()
            for l in _git(self.repo, "diff", "--name-only", "--diff-filter=U", check=False).stdout.splitlines()
            if l.strip()
        ]
        _git(self.repo, "merge", "--abort", check=False)
        return MergeResult(
            story_id,
            branch,
            False,
            conflicts=conflicts,
            message=(proc.stderr or proc.stdout).strip(),
        )

    def merge_wave(self, story_ids: list[str], *, into: str | None = None) -> list[MergeResult]:
        """Merge an entire wave, **sequentially** in the order given.

        Stops at the first conflict: merging further on top of a conflicted
        tree only makes root-cause analysis harder.
        """
        results: list[MergeResult] = []
        for sid in story_ids:
            r = self.merge_story(sid, into=into)
            results.append(r)
            if not r.merged:
                break
        return results

    # ------------------------------------------------------------ internals

    def _ensure_root(self) -> None:
        """Create the worktree directory and **self-exclude it from git**.

        The worktree directory lives inside the repo, so without ignoring it
        every ``git status`` would show an extra ``?? .aisef/`` line — enough
        to break "clean tree after merge abort" checks and easy to accidentally
        commit. A ``.gitignore`` containing ``*`` inside the directory is the
        cleanest self-exclusion, without modifying the project's ``.gitignore``.
        """
        self.root.mkdir(parents=True, exist_ok=True)
        marker = self.root / ".gitignore"
        if not marker.exists():
            marker.write_text("*\n", encoding="utf-8")

    def _branch_exists(self, branch: str) -> bool:
        return _git(
            self.repo, "rev-parse", "--verify", "--quiet", f"refs/heads/{branch}", check=False
        ).returncode == 0
