"""V2.0 release: the probe capability calibrations the release ships — `aisef2/app/calibrations.py`, the rows static
admission (RFC §12, check 9) reads in every `aisef run` — and their record.

    python -P validation/qualification/release_calibration.py --print   # calibrate, print, write nothing
    python -P validation/qualification/release_calibration.py --write   # -> aisef2/app/calibrations.py and
                                                                        #    closure-evidence/v2/release/PROBE-CALIBRATIONS.json
    python -P validation/qualification/release_calibration.py --check   # the shipped rows are this tree's probes, every
                                                                        # class re-demonstrated (calibrate() runs again)

A row exists only for a contrast demonstrated now (aisef2.probe.calibration.calibrate, §9.1.1): every active probe of
the catalog, every observation class it declares, its committed positive fixture observed SATISFIED and its negative
REFUTED, and the same fixtures rejected once they stop contrasting (negative, negative). A class without fixtures, or
that does not contrast, is a problem and nothing is written. The probes are the ones B1 changed, so the cycle-2
calibration records (bound to the earlier digests) stay as committed, as history.
"""

from __future__ import annotations

import argparse
import dataclasses
import hashlib
import json
import pathlib
import sys
import time

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

SHIPPED_REL = "aisef2/app/calibrations.py"
RECORD_REL = "closure-evidence/v2/release/PROBE-CALIBRATIONS.json"
FIXTURES_REL = "tests/v2/fixtures/calibration"
KEYS = ("probe_id", "probe_digest", "observation_class", "positive_fixture", "negative_fixture")
HEADER = '''"""The probe capability calibrations this release ships: one row per (active probe digest, observation class), each a
contrast demonstrated by aisef2.probe.calibration.calibrate over the committed fixtures named. Static admission (check 9)
admits a spec only with its row. Generated by validation/qualification/release_calibration.py --write; never edited."""

CALIBRATIONS = (
'''


def _sha_tree(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    for p in sorted(x for x in path.rglob("*") if x.is_file() and "__pycache__" not in x.parts):
        h.update(p.relative_to(path).as_posix().encode() + b"\0" + p.read_bytes().replace(b"\r\n", b"\n") + b"\0")
    return h.hexdigest()


def calibrate_all() -> tuple[list[dict], list[str], dict]:
    from aisef2.probe import catalog
    from aisef2.probe.calibration import NotQualified, calibrate, calibration_env
    registry, env = catalog.registry(), calibration_env(sys.executable)
    rows, problems, fixtures = [], [], {}
    for e in catalog.CATALOG:
        if not e.active:
            continue
        probe = e.factory()
        if probe.digest != e.probe_digest:
            problems.append(f"{e.probe_id}: the catalog's digest is not the probe's")
        for cls in e.classes:
            rel = f"{FIXTURES_REL}/{e.fixture_root}/{cls}"
            pos, neg = ROOT / rel / "positive", ROOT / rel / "negative"
            if not (pos.is_dir() and neg.is_dir()):
                problems.append(f"{e.probe_id} {cls}: no committed fixtures at {rel}")
                continue
            fixtures[rel] = {"positive": _sha_tree(pos), "negative": _sha_tree(neg)}
            try:
                rec = calibrate(probe, cls, pos, neg, env, time.time, registry=registry,
                                names=(f"{rel}/positive", f"{rel}/negative"))
            except NotQualified as x:
                problems.append(f"{e.probe_id} {cls}: {x}")
                continue
            rows.append(dataclasses.asdict(rec))
            try:
                calibrate(probe, cls, neg, neg, env, time.time, registry=registry)
                problems.append(f"{e.probe_id} {cls}: a non-contrasting pair (negative, negative) was not rejected")
            except NotQualified:
                pass
    return rows, problems, fixtures


def shipped_source(rows: list[dict]) -> str:
    body = "".join("    " + json.dumps({k: r[k] for k in (*KEYS, "demonstrated_at")}, sort_keys=True) + ",\n" for r in rows)
    return HEADER + body + ")\n"


def record(rows: list[dict], problems: list[str], fixtures: dict) -> dict:
    from validation.qualification import common as C
    return {"record": "AISEF V2.0 — THE PROBE CAPABILITY CALIBRATIONS THE RELEASE SHIPS",
            "generator": {"path": "validation/qualification/release_calibration.py", "sha256": C.lf_sha(HERE / "release_calibration.py")},
            "aisef2_tree": C.git("rev-parse", "HEAD:aisef2"), "shipped": SHIPPED_REL,
            "rows": [{k: r[k] for k in KEYS} for r in rows], "fixtures": fixtures, "problems": problems,
            "verdict": "CALIBRATED" if not problems else "PROBLEMS"}


def check() -> list[str]:
    """The shipped rows are exactly what calibrating this tree gives (without the time), and they contrast now."""
    from aisef2.app import calibrations as shipped
    rows, problems, _ = calibrate_all()
    want = sorted(tuple(r[k] for k in KEYS) for r in rows)
    have = sorted(tuple(r[k] for k in KEYS) for r in shipped.CALIBRATIONS)
    if want != have:
        problems.append(f"{SHIPPED_REL} is not this tree's calibration: {len(have)} rows shipped, {len(want)} derived "
                        f"(missing {sorted(set(want) - set(have))[:3]}, extra {sorted(set(have) - set(want))[:3]})")
    return problems


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--print", action="store_true")
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    if a.check:
        problems = check()
        print("release calibration: " + ("PASS" if not problems else "FAIL\n" + "\n".join(problems)))
        return 1 if problems else 0
    rows, problems, fixtures = calibrate_all()
    rec = record(rows, problems, fixtures)
    if a.print or problems:
        print(json.dumps(rec, indent=1, sort_keys=True))
        return 1 if problems else 0
    (ROOT / SHIPPED_REL).write_text(shipped_source(rows), encoding="utf-8")
    (ROOT / RECORD_REL).parent.mkdir(parents=True, exist_ok=True)
    (ROOT / RECORD_REL).write_text(json.dumps(rec, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {SHIPPED_REL} ({len(rows)} rows) and {RECORD_REL}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
